### PR TITLE
fix: `message_edit` event and edit caption in file 

### LINKED ISSUE #2612: "message_edit" event does not fire on editing image captions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

wbot.on("message_edit" works normally on text only messages, but if you edit an image, and maybe even files with media, it will most of the time not fire any event.

It worked randomly 1 time here, with an image caption, for me, but 90% of the time it does not fire if you edit the caption of an image.
Regular texts do fire normally.

image

### Expected behavior

Expected editing a caption of a file or image to fire the message_edited event.

### Steps to Reproduce the Bug or Issue

 wbot.on("message_edit", async (message, newBody, prevBody) => {
  console.log(
      `Editing Message ${
        (msg.id.id, null, 2)
      }. Prev: ${prevBody}. New: ${newBody}`
    );
  });

send an image with caption, then edit the caption text

### Relevant Code

 wbot.on("message_edit", async (message, newBody, prevBody) => {
  console.log(
      `Editing Message ${
        (msg.id.id, null, 2)
      }. Prev: ${prevBody}. New: ${newBody}`
    );
  });

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Windows & Ubuntu 22
Android Phone
whatsapp-web.js version: most recent github version as of 26/october: specifier: git://github.com/pedroslopez/whatsapp-web.js.git#main
    version: github.com/pedroslopez/whatsapp-web.js/7737a0d701c2bde180c4cdcb2926895b0b649b4f

WhatsApp Web version [run await client.getWWebVersion()]: WWeb v2.2346.52
Node.js Version  v18.16.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tofers**
# PR Details

Whatsapp добавил редактирование описаний в файлах. 

## Description
This is all available in the current method, finalized. 

## Related Issue
closes #2612 

## How Has This Been Tested
Linux, Centos OS

```
NPM: npm i github:tofers/whatsapp-web.js#message_edit
Yarn: yarn add github:tofers/whatsapp-web.js#message_edit
```

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by gkp1** [comment]
nice thanks! hope it gets merged  fast

**Review by shirser121 — APPROVED** [review]
LGTM

**Comment by alechkos** [comment]
I just tested the editing of a text message on wweb v2.2350.52 with:

```js
client.on('message_create', async (message) => {
    if (message.fromMe) {
        await message.edit('new-body');
    }
}
```

The text message is not edited if it is sent from the phone,
made some debugging and saw that [`window.Store.MsgActionChecks.canEditText`](https://github.com/pedroslopez/whatsapp-web.js/pull/2617/files#diff-96082c9140c86e9e199d49b4a854cccb6fec736873b7da536bf2e640f473c9bfR642) returns `false` because of a `message.self` value that is `'in'`, while internal checks require it to be `'out'` for the `true` to be returned
But if the message is sent from the browser with headless false, the message is edited successfully and the `message.self` in this case is `'out'`

I think we need to investigate more but i haven't dived deeper yet

@shirser121, did you succeed in editing the message?

**Review by alechkos — CHANGES_REQUESTED** [review]
@tofers 
Can you please approve these suggested changes, I combined `change:body` and `change:caption` into one line since those two fire the same `onEditMessageEvent` event.
Tested and works as expected

**Comment by alechkos** [comment]
And also please add
```js
* @fires Client#message_edit
```
after [this](https://github.com/tofers/whatsapp-web.js/blob/d8cefba5a50c794fc786f41c438d8cc1ce25d9cd/src/Client.js#L41) line in `Client.js`

**Review by alechkos — APPROVED** [review]

**Pull request merged**
