### PR TITLE
Fix for "Cannot read mediaData of undefined"

### LINKED ISSUE #298: Message.downloadMedia() is throwing "Error: Evaluation failed: Object"
### Bug description
When I call message.downloadMedia(), for some messages (not all of them) puppeteer throws an error. In this specific case, it is an Image message.
I found out that for my specific case, this image was not in my phone anymore. Whatsapp web (in the browser) shows the following message when I try to open it: "Photo Unavailable. Can't view this photo because it's no longer on your phone."
I believe that instead of throwing an error like the one bellow, simply a null value should be returned. Or maybe an error with a better error message should be thrown.

Bellow the full error message. Note: I just replaced all occurences of my local project folder path with `<project_folder>`

```
(node:7836) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Object
    at ExecutionContext._evaluateInternal (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at ExecutionContext.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
    at Message.downloadMedia (<project_folder>\node_modules\whatsapp-web.js\src\structures\Message.js:202:24)
  -- ASYNC --
    at ExecutionContext.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:95:27)
    at Message.downloadMedia (<project_folder>\node_modules\whatsapp-web.js\src\structures\Message.js:202:50)
    at ChatBotWhatsappServer.<anonymous> (<project_folder>\src\chatbot\channels\whatsapp\ChatBotWhatsappServer.ts:449:47)
    at Generator.next (<anonymous>)
    at fulfilled (<project_folder>\node_modules\tslib\tslib.js:112:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:7836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

### Reproduction steps
1. Fetch messages from a chat
2. For all the messages that have `hasMedia === true`, call downloadMedia()

### Expected behavior 
A null value should be returned for a file that does not exist in the phone, or a better error message should be thrown.

### Environment (please complete the following information):
**WhatsApp**
 - Account type: Business
 - Device OS: Android
 - WhatsApp Web version: 2.2031.4

**Library**
 - Browser: Chromium
 - NodeJS version (`node -v`): v12.14.1
 - npm or yarn version (`npm -v`): v6.14.4
 - whatsapp-web.js version: v1.7.0

### Related issues
#283

### LINKED ISSUE #674: msg.downloadMedia() throws 'Error: Evaluation failed: Object' when media is out of cache
### Bug description

Executing the following code sometimes provides the error listed in the second block. The `msg.mediaKey` prevents images that have been deleted from the chat to be processed, even if in theory the message evaluates as true in the `msg.hasMedia`. However when a message has media and that media is accessible is only downloaded if the file is recent. Old messages with available images in whastapp web cannot be accessed.

```javascript
let messages = await this_chat.fetchMessages({limit: Infinity});

for (let index = 0; index < messages.length; index++)
{
    let msg = messages[index];

    if (msg.hasMedia)
    {
        if (msg.mediaKey !== undefined)
        {
            let attachmentData = await msg.downloadMedia()
        }
    }
}
```

The error itself:
```
Error: Evaluation failed: Object
    at ExecutionContext._evaluateInternal (C:\Whatsapp_test\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (C:\Whatsapp_test\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Message.downloadMedia (C:\Whatsapp_test\src\structures\Message.js:243:24)
    at async **C:\Whatsapp_test\example.js:358:58**
```

### Expected behavior 
If a message of the chat contains media, and this media is indeed accessible from within whatsapp web but is not necessarily recent, the library should be able to download this data

### Environment:
**WhatsApp**
 - Account type: Standard 
 - Device OS: Android
 - WhatsApp Web version: 2.2119.6

**Library**
 - Browser: Chromium
 - NodeJS version: v15.11.0
 - npm or yarn version: 7.6.0
 - whatsapp-web.js version: 1.12.6

### LINKED ISSUE #687: cannot download media from quoted message
### Bug description

When you call downloadMedia() in a message object obtained through "getQuotedMessage()" you get an error.

### Reproduction steps
1. get any message with quoted message attached
2. get quoted message through getQuotedMessage();
3. call downloadMedia() on quoted message

### Expected behavior 

receive MessageMedia object

### Relevant code

example code:

const original_msg; (Message)
const quoted_msg = original_msg.getQuotedMessage();
const media = quoted_msg.downloadMedia();

error given:

Error: Evaluation failed: TypeError: Cannot read property 'mediaData' of undefined
    at __puppeteer_evaluation_script__:4:21
    at ExecutionContext._evaluateInternal (/cird-instance/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/cird-instance/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    ...

### Environment (please complete the following information):
**WhatsApp**
 - Account type = tested with both user and business
 - Device OS = Android
 - WhatsApp Web version = 2.2121.5

**Library**
 - Browser = Chrome
 - NodeJS version (`node -v`) = 16.2
 - npm or yarn version (`npm -v`):
 - whatsapp-web.js version: 1.12.5

### Additional context

IMPORTANT: I't seems it only happens when the quoted message is old

### PR DESCRIPTION
**Pull request by Darker935**

### CODE REVIEW

**Review by purpshell — COMMENTED** [review]
I suggest that instead of fully relying on this.data, we should instead use it in case of an error. This allows for dynamic media to be viewed whilst the message is actually in cache

**Comment by pedroslopez** [comment]
When exactly is this issue happening? 

Also, the call to `msg.downloadMedia()` was added to fix an issue with downloading old media in certain cases, so we may still need that (this is why we need tests)

**Comment by PurpShell** [comment]
> When exactly is this issue happening?
> 
> Also, the call to `msg.downloadMedia()` was added to fix an issue with downloading old media in certain cases, so we may still need that (this is why we need tests)

the error occurs when the media becomes out of cache

**Review by purpshell — APPROVED** [review]

**Comment by PurpShell** [comment]
rather the message containing media being out of cache

**Comment by PurpShell** [comment]
so just using past information from the cache in node would work

**Comment by PurpShell** [comment]
Un-stale

**Comment by pedroslopez** [comment]
The downloadMedia function has changed- I think we can do a similar approach for the new one though, saving the properties that `downloadAndDecrypt` needs.

I'm still not sure how to reproduce this. Please write some clear steps that lead to the issue (if still applicable) to verify the behavior and get this fixed.

Thanks!

**Comment by PurpShell** [comment]
> The downloadMedia function has changed- I think we can do a similar approach for the new one though, saving the properties that `downloadAndDecrypt` needs.
> 
> I'm still not sure how to reproduce this. Please write some clear steps that lead to the issue (if still applicable) to verify the behavior and get this fixed.
> 
> Thanks!

When a message goes out-of-cache, it's certainly found in Node's cache, though Store no longer has the message. In the past, we'd handle the error and ask users to re-send media (when they quote the message), but it's certain that between the message got received. Though most bots are online enough to keep a steady Node cache, so we can use the properties we have in Node, and download from there.

As for if this still works, you have to wait for Quishot's answer.

**Comment by gkp1** [comment]
> I'm still not sure how to reproduce this. Please write some clear steps that lead to the issue (if still applicable) to verify the behavior and get this fixed.

This is still happening. 2 steps: 1st, Get a quoted message, 2nd: do quotedMessage.downloadMedia(). --> error.

Another issue, 'sendMediaAsSticker' is not working properly when you use mimetype video/mp4 and base64 data of a video, ffmpeg says invalid input. Sadly I don't know how to fix either, so just reporting

**Pull request closed without merging**
