### PR TITLE
fix: Get Number Id

### PR DESCRIPTION
**Pull request by CYJun-1223**

### CODE REVIEW

**Comment by guicuton** [comment]
Up

Works like a charm

**Review by guicuton — APPROVED** [review]
Changes succefully tested

**Comment by jtourisNS** [comment]
Pretty sure you can close this as it is a **duplicate** of https://github.com/pedroslopez/whatsapp-web.js/pull/1571

Also, please do not modify the version on future PR

**Review by guicuton — CHANGES_REQUESTED** [review]
As mentioned by @jtourisNS this PR is duplicated.
Original fix on #1571 

Please, close this PR

**Comment by pedroslopez** [comment]
Closed as duplicate of #1571

**Pull request closed without merging**
