### PR TITLE
fix: CallCollection

### LINKED ISSUE #2383: reading 'CallCollection'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It gives an error when scanning the qr code

### Expected behavior

It gives an error when scanning the qr code

### Steps to Reproduce the Bug or Issue

It gives an error when scanning the qr code

### Relevant Code

It gives an error when scanning the qr code

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

It gives an error when scanning the qr code

### Additional context

It gives an error when scanning the qr code

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

### - [How Has the PR Been Tested](#tests)
- [**The environment the PR was tested on**](#env)
- [**I want to test this PR**](#pr-testing)
- [**I have an issue while testing this PR**](#pr-testing-issue)

### - [Types of Changes](#types-of-changes)

---

## Description <a href="#description" id="description"/>
From the **WWeb v2.2333.11-beta** the `CallCollection` module have been changed, the fact caused an issue, this PR fixes the issue.

## Related Issue <a href="#related-issue" id="related-issue"/>
PR fixes #2383

## How Has This Been Tested <a href="#tests" id="tests"/>
Was tested with the following code:
```js
client.on('call', async(call) => {
    console.log(call);
    await call.reject();
});
```
Works as expected.

<details><summary>

### Tested On <a href="#env" id="env"/>
</summary>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS v1.21.1-alpha.0
    - WWeb v2.2333.11-beta
    - Node v16.17.1
    - Chrome 114.0.5735.199
</details>

### To test this PR by yourself you can run one of the following commands: <a href="#pr-testing" id="pr-testing"/>
```powershell
# NPM
npm install github:alechkos/whatsapp-web.js#fix-call-collection
# YARN
yarn add github:alechkos/whatsapp-web.js#fix-call-collection
```

### If you encounter any issues while testing this PR, please provide in a comment: <a href="#pr-testing-issue" id="pr-testing-issue"/>
1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWwebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got

## Types of Changes <a href="#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by shirser121 — APPROVED** [review]
LGTM

**Comment by luanraithz** [comment]
Who else has the permission to review this PR?

**Comment by alechkos** [comment]
@luanraithz 
> Who else has the permission to review this PR? 

Everyone have

**Review by luanraithz — APPROVED** [review]
LGTM

**Comment by luanraithz** [comment]
> @luanraithz
> 
> > Who else has the permission to review this PR?
> 
> Everyone have

Everyone with write permission, apparently

**Comment by alechkos** [comment]
@luanraithz 
> Everyone with write permission, apparently

Everyone can review the pr, this is exactly what you did now, but only maintainers can merge it

**Comment by luanraithz** [comment]
I asked for this reason:
image

**Comment by AndreGraca3** [comment]
image

I installed using the above command, it tells me this error, i believe the version is 1.21.1alpha-0. browser is chrome, headless: true

**Review by paulinhovba — APPROVED** [review]

**Comment by alechkos** [comment]
@tofers 
> This method returns the whole list and Call is there and there. Version comparisons can be omitted

Thank you, fixed

**Comment by GustavoBazinga** [comment]
LGTM

Thank you, bro.

**Comment by paulinhovba** [comment]
Someone can approve this?

**Review by GustAlvesG — APPROVED** [review]

**Review by josethz00 — APPROVED** [review]
LGTM, good job

**Review by josethz00 — APPROVED** [review]

**Review by tuyuribr — APPROVED** [review]

**Comment by xx7Ahmed7xx** [comment]
window.Store.Call = window.WWebJS.compareWwebVersions(window.Debug.VERSION, '<', '2.2333.11-beta')
        ? window.mR.findModule('CallCollection')[0].CallCollection
        : window.mR.findModule((module) => module.default && module.default.Call)[0].default.Call;

I tried this code as provided but it gives the following:
javascript error: Cannot read properties of undefined (reading 'sendMessage')

**Pull request merged**
