### PR TITLE
fix: link retrieval from message

### LINKED ISSUE #1766: msg.links is empty when from .on("message") events
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `client.on("message")` event to get the message I got empty `links` property. 
But when I get from `chat.fetchMessages()` its fine, `links` property appear

### Expected behavior

As user I expected to get `links` property from on message event

### Steps to Reproduce the Bug or Issue

1. Initialize wweb.js as usual
2. use on message event

```js
client.on("message", (msg) => console.log(msg))
```

and test to recieve message which contain link, the result is like this (links empty):

links_empty

3. use chat.fetchMessages()

```js
const chat = await client.getChatById('examplenumber@c.us')
const msgs = await chat.fetchMessages({ limit:1, fromMe:false })
console.log(msgs[0])
console.log(msgs[0].links)
```

and you got the links property appear

links_shown_2

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: `Windows 11`
Phone: `Android 12`
whatsapp-web.js version: `1.18.2`
WhatsApp Web version: `2.2241.7`
Node.js version: `18.10.0`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# Table of Contents

### - [How Has the PR Been Tested](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#tests) (latest test on 14.01.2024) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#tests-b" id="tests-b"/>
- [**The environment the PR was tested on**](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#env)

### - [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#types-of-changes) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#types-of-changes-b" id="types-of-changes-b"/>

---

## [Description](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#description-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#description" id="description"/>
**The PR fixes link retrieval from a message if it contains any.**
Fixed both for outcoming and incoming messages.

---

## [Related Issue](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#related-issues-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#related-issues" id="related-issues"/>
The PR closes #1766

---

## [Usage Example](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#usage-example-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#usage-example" id="usage-example"/>

```js
// client initialization...

client.on('ready', (message) => {
    const chatId = 'XXXXXXXXXX@c.us';

    const noLinks = await client.sendMessage(chatId, 'message without links');
    /**
     * Message {
     *     _data: {
     *       ...
     *       links: []
     *     },
     *     ...
     *     links: []
     *   }
     */
    console.log(noLinks);

    const withLinks = await client.sendMessage(chatId, 'bit.ly');
    /**
     * Message {
     *     _data: {
     *       ...
     *       links: [ { link: 'http://bit.ly', isSuspicious: false } ]
     *     },
     *     ...
     *     links: [ { link: 'http://bit.ly', isSuspicious: false } ]
     *   }
     */
    console.log(withLinks);
});

client.on('message', (message) => {
    /**
     * Let's say the 'message.body' is as follows:
     * "Hey there! These are some links: https://fb.com, fb.com, bit.ly, http://instagram.com", then
     * the output will be as follows:
     * [
     *   { link: 'https://fb.com', isSuspicious: false },
     *   { link: 'http://fb.com', isSuspicious: false },
     *   { link: 'http://bit.ly', isSuspicious: false },
     *   { link: 'http://instagram.com', isSuspicious: false }
     * ]
     */
    console.log(message.links);
});
```

---

## [To test this PR by yourself you can run one of the following commands:](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#pr-testing-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-links
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-links
```

---

## [If you encounter any errors while testing this PR, please provide in a comment:](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#pr-issues-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#pr-issues" id="pr-issues"/>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The error you got
3. The library version
4. The WWeb version: `console.log(await client.getWWebVersion());`
5. The browser (Chrome/Chromium)

> [!IMPORTANT]
> **You have to [reapply](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#pr-testing) the PR each time it is changed (new commits were pushed since your last application)**

---

## [How Has The PR Been Tested](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#tests-b) (latest test on 14.01.2024) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#tests" id="tests"/>
Tested with the code provided in the usage example, both with text and media messages that have links and without.

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10:
    - WhatsApp: **latest**
    - WA Business: **latest**
- Windows 10:
    - WWebJS: **v1.23.1-alpha.3**
    - WWeb: **v2.2402.5**
    - Puppeteer: **v18.2.1**
    - Node: **v18.17.1**
    - Chrome: **latest**

---

## [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#types-of-changes-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2716#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (feature/fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [ ] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

### CODE REVIEW

**Comment by shirser121** [comment]
I think we should keep the object as it was to not break the code

**Comment by alechkos** [comment]
@shirser121 
> [I think we should keep the object as it was to not break the code](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#issuecomment-1886621669)

Agree with you, fixed

**Review by tuyuribr — APPROVED** [review]

**Comment by alechkos** [comment]
@tuyuribr, there are [new changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2716/commits/2952ac62704ec1ee07bfcae7129d6c511b8781d7)

**Comment by shirser121** [comment]
Is that support old node version?
Also, i think that if its a media, its just wasted CPU to looking for links over the base64 preview

**Comment by alechkos** [comment]
@shirser121 
> [Is that support old node version?](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#issuecomment-1890857184)

Yes
> [Also, i think that if its a media, its just wasted CPU to looking for links over the base64 preview](https://github.com/pedroslopez/whatsapp-web.js/pull/2716#issuecomment-1890857184)

[Fixed](https://github.com/pedroslopez/whatsapp-web.js/pull/2716/commits/3fbb29b92ac688344b423ec3350dc798671d9e23)

**Review by shirser121 — APPROVED** [review]
Thanks

**Pull request merged**
