### PR TITLE
Add from which device the message was sent.

### PR DESCRIPTION
**Pull request by tuyuribr**
Use the message Id for fingerprint the device that was being use when the message was sent

### CODE REVIEW

**Comment by pedroslopez** [comment]
This is interesting! How did you determine these things? Is there any reference that this is how it works anywhere in the code or otherwise?

**Comment by tuyuribr** [comment]
> 
> 
> This is interesting! How did you determine these things? Is there any reference that this is how it works anywhere in the code or otherwise?

This is a pattern I found when searching for vulnerabilities in the code, Messages sent by WebW start with 3E, Messages sent by an Iphone start with 3A, messages sent from an Android device are 32 HEX in size.
Isn't documented anywhere but I got 0 errors from my user base ( 1k + )

**Comment by PurpShell** [comment]
Interesting!

**Comment by pedroslopez** [comment]
Seems to work for me!
thanks

**Comment by Kouthk** [comment]
Have these been added to the features documents?

**Pull request merged**
