### PR TITLE
FIx message.delete()

### LINKED ISSUE #1071: Message.delete(true), not working as expected
### Bug description
Message.delete(true) should delete the message from everyone, but it's deleting "from me" instead.

### Reproduction steps
1. get message instance from client
2. use Message.delete(true)

### Expected behavior 
it should delete the message from everyone

### Relevant code
let chats = await webclient.getChatById(searchedchatId);
    let messages = await chats.fetchMessages({ limit: 30 });
    for (let i = 0; i < messages.length; i++) {
      if (messages[i].id._serialized == messageId) {
        try {
        await messages[i].delete(true);  //delete message sent from me for everyone
         resolve({
            sent: true,
            message: 'message deleted',
          });
        } catch (err) {
          resolve({ error: 'Unable to delete message, please check your messageId' });
        }
        break;
      }
    }

### Environment (please complete the following information):
**WhatsApp**
 - Account type [Standard / Business]:Standard
 - Device OS [iOS / Android]:android 
 - WhatsApp Web version [run `await client.getWWebVersion()`]:

**Library**
 - Browser [Chrome / Chromium]:chromium
 - NodeJS version (`node -v`):14.17
 - npm or yarn version (`npm -v`):npm 6.14.15
 - whatsapp-web.js version:1.15.3

**Other**
 - Operating system (the one running node) [Linux / MacOS / Windows]:windows
 - Operating system version (ex. Windows 10):  win 10
### Additional context
MessageId is double checked, it's send from me

### PR DESCRIPTION
**Pull request by shirser121**
Change msg.canRevoke to msg._canRevoke according to WhatsApp code change

### CODE REVIEW

**Review by yoldar — APPROVED** [review]

**Review by purpshell — APPROVED** [review]
LGTM! thanks for the fix

**Review by gididaf — APPROVED** [review]
LGTM

**Comment by w3nder** [comment]
Thanks, here it worked with your fix.

**Comment by Kunalvrm555** [comment]
The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch.
Please check

**Comment by shirser121** [comment]
> The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check

Can you explain what do you mean?

**Comment by Kunalvrm555** [comment]
> > The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check
> 
> Can you explain what do you mean?

#1119 
in messages.js (line 385)

#`            if (everyone && msg.id.fromMe && msg.canRevoke()) {
`
should rather be 
#`            if (everyone && msg.id.fromMe && msg._canRevoke()) {
`

**Comment by shirser121** [comment]
> > > The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check
> > 
> > 
> > Can you explain what do you mean?
> 
> #1119 in messages.js (line 385)
> 
> #` if (everyone && msg.id.fromMe && msg.canRevoke()) {` should rather be #` if (everyone && msg.id.fromMe && msg._canRevoke()) {`

That exactly what we change here

**Comment by Kunalvrm555** [comment]
> > > > The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check
> > > 
> > > 
> > > Can you explain what do you mean?
> > 
> > 
> > #1119 in messages.js (line 385)
> > #` if (everyone && msg.id.fromMe && msg.canRevoke()) {` should rather be #` if (everyone && msg.id.fromMe && msg._canRevoke()) {`
> 
> That exactly what we change here


But the change was not done in the main branch. The file `src/structures/messages.js` still has the issue.

**Comment by shirser121** [comment]
> > > > > The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check
> > > > 
> > > > 
> > > > Can you explain what do you mean?
> > > 
> > > 
> > > #1119 in messages.js (line 385)
> > > #` if (everyone && msg.id.fromMe && msg.canRevoke()) {` should rather be #` if (everyone && msg.id.fromMe && msg._canRevoke()) {`
> > 
> > 
> > That exactly what we change here
> 
> But the change was not done in the main branch. The file `src/structures/messages.js` still has the issue.

Just because it's not merge with the main branch

**Comment by Kunalvrm555** [comment]
> > > > > > The change from msg.canRevoke() to msg._canRevoke() is not reflecting in the main branch. Please check
> > > > > 
> > > > > 
> > > > > Can you explain what do you mean?
> > > > 
> > > > 
> > > > #1119 in messages.js (line 385)
> > > > #` if (everyone && msg.id.fromMe && msg.canRevoke()) {` should rather be #` if (everyone && msg.id.fromMe && msg._canRevoke()) {`
> > > 
> > > 
> > > That exactly what we change here
> > 
> > 
> > But the change was not done in the main branch. The file `src/structures/messages.js` still has the issue.
> 
> Just because it's not merge with the main branch

It needs to be merged then. upon deployment, the main branch is used for npm packages installation and therefore, throws errors. I had to fork and make changes to the repo to use it in my code

**Review by fogolin — APPROVED** [review]

**Review by igortrust — APPROVED** [review]
test ok

**Comment by fogolin** [comment]
> 

Same thing here, needed to fork the project to get it working.

**Review by w3nder — APPROVED** [review]
LGTM

**Review by kellyiscute — APPROVED** [review]

**Review by menezesbr — APPROVED** [review]

**Review by su-chang — APPROVED** [review]
LGTM

**Comment by yoldar** [comment]
LGTM

**Review by pedroslopez — APPROVED** [review]
Thanks for this!

**Pull request merged**
