### PR TITLE
Automaticaly format audio to ogg/opus

### PR DESCRIPTION
**Pull request by Helvio88**
# PR Details

Re-creation of PR #1907
Sending audio through wwebjs is not very reliable, as WhatsApp needs a very specific format

## Description

Added ffmpeg conversion in the Util class and automatic detection of mime for efficient conversion in sendMessage()

## Related Issue

#1625 
#1584 
#1813 

## Motivation and Context

I wanted to seamlessly send an audio via wwebjs like it happens with Stickers.
I am using ffmpeg to convert an mp3 file into ogg/opus and it works.
Wanted everyone to benefit from it, too.

## How Has This Been Tested

I have not tested the code I sent you, but I have done the conversion in a similar fashion in my code, essentially proxying all the Audio and PTT messages through it. It works.

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by Helvio88** [comment]
@tuyuribr - I have re-created this PR, because I pushed commits I didn't want to in the other one. I closed #1907.

FYI, all the `ffmpeg` code follows the *exact* guidelines as lines 93-120, including temp file generation, reject and resolve. I would think it's best to keep it this way, for standardization. If changes are required, I'd suggest they be made after this PR is merged, and in all the similar functions in this file.

**Comment by tofers** [comment]
I wouldn't put that into processing, sometimes you just need to send mp3. 

As a help for voice, fine, but I would rather recommend processing audio/video before sending to put less stress on your container load and memory consumption

**Comment by Helvio88** [comment]
I think the approach should be transparent - therefore I added a check to see if `sendAudioAsVoice` is set and convert accordingly. See latest commit.

**Review by purpshell — COMMENTED** [review]
I suggest more testing is done here, many audio formats can't be moved into opus/ogg with ffmpeg, I've hit such a roadblock before. I suggest you keep on using ffmpeg though, as it has a uniform and expected response.

**Comment by PurpShell** [comment]
> I think the approach should be transparent - therefore I added a check to see if `sendAudioAsVoice` is set and convert accordingly. See latest commit.

Please add more documentation regarding its behavior, readers of the documentation should know what is happening here

**Comment by tofers** [comment]
I apologize of course, maybe I seem rude. But even so, I would have to rewrite my application and write a crutch to get around this conversion.

For two years I have been sending voice messages in mp3 format

**Pull request closed without merging**
