### PR TITLE
fix: Error: Evaluation failed: TypeError: e.isLid is not a function

### LINKED ISSUE #1569: Error: Evaluation failed: TypeError: e.isLid is not a function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

production.ERROR: log_error_Array
(
    [function] => whatsApp
    [error] => Error: Evaluation failed: TypeError: e.isLid is not a function

### Expected behavior

sendMessage

### Steps to Reproduce the Bug or Issue

production.ERROR: log_error_Array
    [function] => whatsApp
    [error] => Error: Evaluation failed: TypeError: e.isLid is not a function

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

OS: Windows
Phone OS: iOS
whatsapp-web.js version:
WhatsApp Web version: 
Node.js Version: 14.18.0

### Additional context

_No response_

### LINKED ISSUE #1576: Check Registered Number Not Respond
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Check Registered Number Not Respond

### Expected behavior

Improvements to the system of checking numbers registered on whatsapp

### Steps to Reproduce the Bug or Issue

When sending a message stuck because I couldn't check the whatsapp number

### Relevant Code

// Send message
app.post('/messages/send-text', [
  body('to').notEmpty(),
  body('message').notEmpty(),
], async (req, res) => {
  const errors = validationResult(req).formatWith(({
    msg
  }) => {
    return msg;
  });

  if (!errors.isEmpty()) {
    return res.status(422).json({
      status: false,
      message: errors.mapped()
    });
  }

  const number = phoneNumberFormatter(req.body.to);
  const message = req.body.message;

  const isRegisteredNumber = await checkRegisteredNumber(number);

  if (!isRegisteredNumber) {
    return res.status(422).json({
      status: false,
      message: 'The number is not registered'
    });
  }

  client.sendMessage(number, message).then(response => {
    res.status(200).json({
      status: true,
      response: response
    });
  }).catch(err => {
    res.status(500).json({
      status: false,
      response: err
    });
  });
});

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

OS : Ubuntu 20.04 (LTS) x64
Phone OS : Android
whatsapp-web.js : 1.17.0
Node.js Version : v12.22.12

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jtouris**
Fix for `Error: Evaluation failed: TypeError: e.isLid is not a function` on `getNumberId`

Credits to: **Pasha_Stifler**

### CODE REVIEW

**Review by unilogica — APPROVED** [review]
Worked for me

**Review by purpshell — APPROVED** [review]
looks good to me

**Comment by wemersonrv** [comment]
> 

No. Just for direct contacts

**Comment by pedropuppim** [comment]
It worked

**Comment by wemersonrv** [comment]
> 

Is not in the WWeb-js lib original Client class because i have a lot of servers and many of them are still in old wweb version yet, so i've made myself a custom method to support both versions:

```js
async function myCustomGetNumberId(number) {

  // currentVersion is WhatsApp Web version previously recovered from client
  // my client is global and initialized before
  const parts = currentVersion?.split('.') ?? 0
  const minor = parseInt(parts[1] ?? '0')

  // Before v2.2224.X
  if (minor < 2224) return await client.getNumberId(number) // Use old version

  // After (>= 2224.X)
  if (!number.endsWith('@c.us')) {
    number += '@c.us'
  }

  return await client.pupPage.evaluate(async (number) => {
    const wid = window.Store.WidFactory.createWid(number)
    const result = await window.Store.QueryExist(wid)
    if (!result || result.wid === undefined) return null
    return result.wid
  }, number)
}
```

**Comment by devnullsans** [comment]
This fix worked for me !
Thank You @jtourisNS

**Review by guicuton — APPROVED** [review]
Works lis a charm on business and non-business account for individual chats.

**Review by filipeborelli — APPROVED** [review]

**Comment by filipeborelli** [comment]
Work.

**Review by herduin — APPROVED** [review]
Despues de realizar pruebas funciona correctamente.

**Comment by laar789** [comment]
Works for me too!

**Comment by tonvital** [comment]
Works like a charm!

**Review by pedroslopez — APPROVED** [review]

**Pull request merged**
