### PR TITLE
fix: message.getLinks is not a function & chat.isEphemeralSettingOn is not a function

### PR DESCRIPTION
**Pull request by Eonus21**

### CODE REVIEW

**Review by Shinhwe — COMMENTED** [review]
consider change to 
msg.links = (message.getRawLinks?.() || []).map(/ some code here/)

**Review by fabiomello — APPROVED** [review]

**Review by brunogui0812 — APPROVED** [review]

**Review by nistarok — APPROVED** [review]

**Review by StefanoVe — APPROVED** [review]

**Review by janke184 — APPROVED** [review]

**Review by hchiapella — APPROVED** [review]

**Review by hchiapella — APPROVED** [review]

**Comment by fabiodevn1** [comment]
save my life

**Review by fabiotgk — APPROVED** [review]
Its Work

**Review by steffany-cruz — APPROVED** [review]

**Review by gabrielromanosec — APPROVED** [review]
ok

**Comment by tuyuribr** [comment]
image
Can we fix the "This message wont disapear"?

**Review by tuyuribr — APPROVED** [review]
We should try to fix the "This message won't disappear" but I'm approving so we can still use the lib

**Comment by tuyuribr** [comment]
eslint too

**Comment by matricce** [comment]
I think we have a good candidate to fix these errors here..
https://github.com/pedroslopez/whatsapp-web.js/compare/main...Julzk:whatsapp-web.js:main

**Comment by pedroslopez** [comment]
Thanks! Worked on an updated fix here to handle properly sending ephemeral messages #1752

**Pull request closed without merging**
