### PR TITLE
Update Injected.js

### PR DESCRIPTION
**Pull request by allburov**
# PR Details

Add change to support WAWEB 2.3000 on injected.js and LocalWebCache.js
A bit different version from https://github.com/pedroslopez/whatsapp-web.js/pull/2825 - it doesn't have long lines with all conditions inlined and uses `ModuleFinder` classes which we can create when there's new not supported changes in modules

## Description

follow the WAWEB 2.3000 change on the function structure, and keep it useable with the old WAWEB version

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by FranciscoJelou — APPROVED** [review]
It worked correctly, thank you very much

**Comment by marcelinopedro** [comment]
**Hi, it stopped giving the error:**

_node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')_

**And the error started:**

node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')
    at fillModuleArray (eval at <anonymous> (:46:5), <anonymous>:6:74)
    at moduleRaid (eval at <anonymous> (:46:5), <anonymous>:15:3)
    at __puppeteer_evaluation_script__:48:17

**Comment by allburov** [comment]
>Hi, it stopped giving the error:

What version of whatsapp web does it give and at which step? 
I've tested it with `2.3000.1012140169` and `2.2411.2`  - works fine

**Comment by maunklana** [comment]
> **Hi, it stopped giving the error:**
> 
> _node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34 const version = indexHtml.match(/manifest-([\d\.]+).json/)[1]; ^
> 
> TypeError: Cannot read properties of null (reading '1')_
> 
> **And the error started:**
> 
> node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221 throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails)); ^
> 
> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push') at fillModuleArray (eval at (:46:5), :6:74) at moduleRaid (eval at (:46:5), :15:3) at **puppeteer_evaluation_script**:48:17

make sure u use this [wwebjs/moduleRaid](https://github.com/wwebjs/moduleRaid)

**Comment by luiscuriel** [comment]
This fixes connection errors and the client starts ok, but I get this error when sending message:
window.Store.MsgKey is not a constructor

**Comment by marcelinopedro** [comment]
Boys and girls,
I speak from here in Brazil 🇧🇷

The problem was resolved perfectly due to these resolutions:
• wweb-js version: '2.2411.2'

• In src/util/constants.js to replace:
webVersionCache: {
                type: 'remote',
                remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html',
            }

• And #2827

Thank you all for the attention!
Sincerely, Pedro Marcelino

**Comment by developer-abdul** [comment]
Just adding the parameter to webVersion with value '2.2411.2' is working fine on my end.

If I don't pass the parameter, I get TypeError: Cannot read properties of null (reading '1') error.

**Comment by vitorsilvalima** [comment]
I still receiving even after updating the injected.js and moduleraid scripts

```
error loading', error: TypeError: Cannot read properties of undefined (reading 'push')
whatsapp-bot-entrypoint.js:3 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Msg')
    at Jt.initialize (whatsapp-bot-entrypoint.js:3:148835)
    at whatsapp-bot-entrypoint.js:5:1820
```

**Comment by Har1ha** [comment]
> Boys and girls, I speak from here in Brazil 🇧🇷
> 
> The problem was resolved perfectly due to these resolutions: • wweb-js version: '2.2411.2'
> 
> • In src/util/constants.js to replace: webVersionCache: { type: 'remote', remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html', }
> 
> • And #2827
> 
> Thank you all for the attention! Sincerely, Pedro Marcelino

can you please describe how you fixed it

**Comment by Har1ha** [comment]
Hello a new error arose following your step please help
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Call')

**Comment by Har1ha** [comment]
> Just adding the parameter to webVersion with value '2.2411.2' is working fine on my end.
> 
> If I don't pass the parameter, I get TypeError: Cannot read properties of null (reading '1') error.

where exactly did you pass the parameter when I set the webVersion in client parameter it does not change the version please help

**Comment by Ramon-Wong** [comment]
> Boys and girls, I speak from here in Brazil 🇧🇷
> 
> The problem was resolved perfectly due to these resolutions: • wweb-js version: '2.2411.2'
> 
> • In src/util/constants.js to replace: webVersionCache: { type: 'remote', remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html', }
> 
> • And #2827
> 
> Thank you all for the attention! Sincerely, Pedro Marcelino

HEY, Muito Obrigado!!
It works!

**Comment by rohankm** [comment]
can someone build a docker image of this pr?

**Review by purpshell — CHANGES_REQUESTED** [review]
relies on client revision and patched moduleRaid (moduleRaid is to be gone soon)

**Comment by hazuer** [comment]
> Boys and girls, I speak from here in Brazil 🇧🇷
> 
> The problem was resolved perfectly due to these resolutions: • wweb-js version: '2.2411.2'
> 
> • In src/util/constants.js to replace: webVersionCache: { type: 'remote', remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html', }
> 
> • And #2827
> 
> Thank you all for the attention! Sincerely, Pedro Marcelino

It's Works, Thanks

**Comment by PurpShell** [comment]
obsolete, follow main PR.

**Comment by stexrbnblack** [comment]
help pease...


Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')
    at fillModuleArray (eval at <anonymous> (:2:5), <anonymous>:6:74)
    at moduleRaid (eval at <anonymous> (:2:5), <anonymous>:15:3)
    at pptr://__puppeteer_evaluation_script__:4:17
    at ExecutionContext._ExecutionContext_evaluate (D:\Proyects\JAVASCRIPT - Chat-Bot-WhatsApp\Chat-Bot_Whatsapp01\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\Proyects\JAVASCRIPT - Chat-Bot-WhatsApp\Chat-Bot_Whatsapp01\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)        
    at async Client.initialize (D:\Proyects\JAVASCRIPT - Chat-Bot-WhatsApp\Chat-Bot_Whatsapp01\node_modules\whatsapp-web.js\src\Client.js:340:9)

**Pull request closed without merging**
