### PR TITLE
Fix: Cannot read properties of undefined (reading 'getProfilePicFull')

### PR DESCRIPTION
**Pull request by jtouris**
Module Fix applied for error:

`Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getProfilePicFull')`

### CODE REVIEW

**Review by LuisWichoGt — APPROVED** [review]
Si se corrigio el error

**Comment by dxversity** [comment]
It works, thanks

**Review by zulfio — APPROVED** [review]
thanks, it's work!

**Comment by selamethanafi** [comment]
thanks, it works!

**Review by aliefdany — APPROVED** [review]
idk but it works!

**Review by pedroslopez — APPROVED** [review]
Thanks! Made a few changes to ensure we get the right module (it could potentially find `Wap` instead in some cases) and simplified the `getProfilePicUrl` function a bit since the called function is now MD-safe.

**Comment by jtourisNS** [comment]
@pedroslopez Awesome! Shouldn't the mentioned issues be associated to the PR so they can be closed?

**Review by Ir001 — COMMENTED** [review]
Thanks, its work

**Pull request merged**
