### PR TITLE
Get Orders and Products

### PR DESCRIPTION
**Pull request by renjop**
For WhatsApp Business users, you are able to get information about any order placed from the catalog window.
image

### CODE REVIEW

**Comment by PurpShell** [comment]
> For WhatsApp Business users, you are able to get information about any order placed from the catalog window.
> image

this also works on other clients, 
but like orders are only for WhatsApp bussiness, except that if client is placing order

**Comment by PurpShell** [comment]
I am going to look into the source, there are some more juicy promising functions we can add.

**Review by KeruMx — APPROVED** [review]

**Comment by PurpShell** [comment]
> but like orders are only for WhatsApp bussiness, except that if client is placing order

and in client is placing order i meant the bot

**Comment by joemags-apps** [comment]
Is this feature still available?
i.e `getOrder`

**Comment by renjop** [comment]
> 
> 
> Is this feature still available?
> i.e `getOrder`

Hi, 
This feature is only available for WhatsApp Business users.

Best Regards,

**Comment by joemags-apps** [comment]
I have tried with WhatsApp business, its not working, can you put a sample
code of using it i.e on message => how do I get the order?

Thanks for your quick response.

**Comment by renjop** [comment]
Hi,
```javascript
client.on('message', async message => {
     if (message.type === MessageTypes.ORDER) {
                let order = await message.getOrder();
     }
});
```

**Comment by joemags-apps** [comment]
> Hi,
> 
> ```js
> client.on('message', async message => {
>      if (message.type === MessageTypes.ORDER) {
>                 let order = await message.getOrder();
>      }
> });
> ```
Hi, thanks again. Is it the version I'm using,  MessageTypes. ``` ORDER ``` is not auto completing. I'm on ``` "whatsapp-web.js": "^1.12.6" ```
image

**Comment by renjop** [comment]
Hi,
This only works on the forked version, it has not been pushed back onto the master branch, that is why it doesn't work or autocomplete. You have to either pull my forked version or wait until someone pulls it back to the master branch.

**Comment by joemags-apps** [comment]
> Hi,
> This only works on the forked version, it has not been pushed back onto the master branch, that is why it doesn't work or autocomplete. You have to either pull my forked version or wait until someone pulls it back to the master branch.

Thank you, how can I do that?  If you can provide a command

**Review by joemunapo — APPROVED** [review]

**Comment by joemags-apps** [comment]
> Hi,
> This only works on the forked version, it has not been pushed back onto the master branch, that is why it doesn't work or autocomplete. You have to either pull my forked version or wait until someone pulls it back to the master branch.

Hi again, can you help me with how I can use your pull request at the moment within my project?

**Comment by pedroslopez** [comment]
Thanks for adding this! I don't think getting individual products for a specific message is implemented here, but we can add it in another PR.

**Comment by renjop** [comment]
Just a couple of comments, 
`this.hasMedia = (data.clientUrl || data.deprecatedMms3Url) && data.type !== MessageTypes.PRODUCT; `
is required because when a client send a product, it has media, but no clientUrl is set and the product image is on the message body `this.body = this.hasMedia && data.type !== MessageTypes.PRODUCT ? data.caption || '' : data.body || '';` and the image is base64encoded

**Comment by pedroslopez** [comment]
> Just a couple of comments,
> `this.hasMedia = (data.clientUrl || data.deprecatedMms3Url) && data.type !== MessageTypes.PRODUCT; `
> is required because when a client send a product, it has media, but no clientUrl is set and the product image is on the message body `this.body = this.hasMedia && data.type !== MessageTypes.PRODUCT ? data.caption || '' : data.body || '';` and the image is base64encoded

When I tested this I was able to get the media just fine with `msg.downloadMedia()`, and it did have a clientUrl. Could you try this again?

**Comment by renjop** [comment]
Must changed since I tried it, seems to be working

**Pull request merged**
