### PR TITLE
fix: sending locations

### LINKED ISSUE #1591: Sending a location message doesn't work!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No working send to location
Example after working
client.sendMessage(numId,new Location(37.422, -122.084, 'Googleplex\nGoogle Headquarters'))
other example
var loc = await new Location(Number(lati),Number(long), '')
client.sendMessage(numId,loc)

### Expected behavior

Send to location in the whatsapp

### Steps to Reproduce the Bug or Issue

client.sendMessage(numId,new Location(37.422, -122.084, 'Googleplex\nGoogle Headquarters'))

### Relevant Code

client.sendMessage(numId,new Location(37.422, -122.084, 'Googleplex\nGoogle Headquarters'))
other example
var loc = await new Location(Number(lati),Number(long), '')
client.sendMessage(numId,loc)

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

linux, whatsapp-web.js@1.17.1

### Additional context

_No response_

### LINKED ISSUE #1888: cannot get data location from client (msg.location not work)
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

msg.location cannot work so the output just blank
I been try msg.body.location but still cannot get the data

### Expected behavior

msg.location cannot work properly

### Steps to Reproduce the Bug or Issue

1. msg.location
2.  blank

### Relevant Code

msg.location

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

-

### Additional context

_No response_

### LINKED ISSUE #2204: Cannot send Location
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When sending a location, it normally appears in the sender's browser chat as if it were sent, but the other person does not receive anything!

### Expected behavior

As a user I hope to send location and the other person will receive that location on the other side on their device

### Steps to Reproduce the Bug or Issue

1. Run script and send Location
2. See the Sender chat
3. See the Destinatary chat

### Relevant Code

```js
const { Client, LocalAuth, Location } = require('whatsapp-web.js');

const client = new Client({
    authStrategy: new LocalAuth(),
    puppeteer: { 
        headless: false
    }
});

client.on('qr', (qr) => {
    console.log('QR RECEIVED', qr);
});

client.on('ready', async () => {
    console.log('READY');
    client.sendMessage("XXXXXXXXXXXX@c.us", new Location(37.422, -122.084, 'Googleplex\nGoogle Headquarters'));
});

client.initialize();
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Windows
Phone OS: Android
whatsapp-web.js version 1.19.5
WhatsApp Web version 2.2320.10
Node.js Version 18.12.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
> [!IMPORTANT]
> https://github.com/pedroslopez/whatsapp-web.js/labels/Breaking%20change

# Table of Contents <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc" id="toc"/>

### - [How Has the PR Been Tested (latest test on 14.08.2023)](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#tests)
- [**The environment the PR was tested on**](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#env)
- [**I want to test this PR**](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#pr-testing)
- [**I have an issue while testing this PR**](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#pr-testing-issue)

### - [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#types-of-changes)

---

## Description [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#description" id="description"/>
PR fixes the functionality of sending the locations.

The constructor of the `Location` class now takes three parameters:
1. Latitude
2. Longitude
3. Additional `options` object with properties:
    - name
    - address
    - URL (if only the URL is passed, the location will be sent as if without the URL)

Since locations have not been working since July last year and users have not used them, it is highly unlikely that these changes will break anyone's functionality, but still.

## Special Thanks
- @PurpShell fot his implementation of the [`injectToFunction()`](https://github.com/pedroslopez/whatsapp-web.js/pull/1636/commits/81111faa058d8e715285a2bfc9a42636074f7c3d#diff-de25cb4b9105890088bb033eac000d1dd2104d3498a8523082dc7eaf319738b8R75-R78)
- @edgardmessias for his implementation of the [fix](https://github.com/wppconnect-team/wa-js/commit/4b0766323291a105b11e75979ff3033964205732), without which the sending of locations would not have occurred

## Related Issues [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#related-issues" id="related-issues"/>
PR fixes #1591 fixes #1888 fixes #2204

## Usage Example [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#usage-example" id="usage-example"/>

```js
client.on('message', async (msg) => {
    if (msg.body === '!location') {
        // only latitude and longitude
        await msg.reply(new Location(37.422, -122.084));
        // location with name only
        await msg.reply(new Location(37.422, -122.084, { name: 'Googleplex' }));
        // location with address only
        await msg.reply(new Location(37.422, -122.084, { address: '1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA' }));
        // location with name, address and url
        await msg.reply(new Location(37.422, -122.084, { name: 'Googleplex', address: '1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA', url: 'google.com' }));
    }
});
```

## How Has This Been Tested [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#tests" id="tests"/>
Was tested with a code provided in usage example.

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS&ensp;&ensp;&ensp;&ensp;**v1.22.1**
    - WWeb&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;**v2.2333.11**
    - Puppeteer&ensp;&ensp;&ensp;**v13.0.0**&ensp;&ensp;|&ensp;&ensp;**v18.2.1**
    - Node&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;**v16.17.1**&ensp;&ensp;|&ensp;&ensp;**v18.17.1**
    - Chrome&ensp;&ensp;&ensp;&ensp;&ensp;**v115.0.5790.171**

### To test this PR by yourself you can run one of the following commands: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-locations
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-locations
```
<details><summary>

### If you encounter any issues while testing this PR, please provide in a comment (click to expand): <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#pr-testing-issue" id="pr-testing-issue"/>
</summary>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWwebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got
</details>

## Types of Changes [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2339#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2339#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [X] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

### CODE REVIEW

**Review by pedroherpeto — APPROVED** [review]

**Comment by edgardmessias** [comment]
😄

**Comment by T3uZ** [comment]
Good morning, does this fix include the contact fix as well?

**Comment by alechkos** [comment]
@T3uZ Hi
> does this fix include the contact fix as well?

No, only the fix for locations
but you can apply the branch which combines all my pr's including the fix for contact and locations

```powershell
npm install github:alechkos/whatsapp-web.js#xukcpn
```

**Comment by T3uZ** [comment]
> @T3uZ Hi
> 
> > does this fix include the contact fix as well?
> 
> No, only the fix for locations but you can apply the branch which combines all my pr's including the fix for contact and locations
> 
> ```powershell
> npm install github:alechkos/whatsapp-web.js#xukcpn
> ```
Screenshot_2

Good morning,
I'm getting an error when I try to use this fix.

**Comment by alechkos** [comment]
@T3uZ 
> I'm getting an error when I try to use this fix.

Most likely this is due to the fact that in the latest versions of the WWeb the module used in the fix was modified / removed, in any case the fix was tested on version 2.2327.4 and you need to use it.
To check your currently used WWeb version:
```js
console.log(await client.getWwebVersion());
```
To load a specific WWeb version: #1847

**Review by keelvin — APPROVED** [review]

**Comment by volkantopal** [comment]
File submission does not work when I use this fix.
=> await sessions[From].sendMessage(To, File)
To = Number
File = jpg Link.

**Comment by alechkos** [comment]
@volkantopal 
> File submission does not work when I use this fix.

This is not related to this PR, check your code.

**Comment by alechkos** [comment]
@volkantopal 
> File submission does not work when I use this fix.

Your issue is not related to this PR, check your code.

**Review by tuyuribr — APPROVED** [review]

**Review by keelvin — APPROVED** [review]

**Comment by alechkos** [comment]
@shirser121 @aliyss

**Review by aliyss — APPROVED** [review]
lgtm

Also very clean code.

**Comment by shirser121** [comment]
Thanks?

**Pull request merged**
