### PR TITLE
Update pupperteer lib

### PR DESCRIPTION
**Pull request by matheust3**
# PR Details

Pupperteer to ^19.4.0

## Motivation and Context

My application was not working due to pupperteer in nodejs v18.12.1

So with the latest version of puppeteer everything is back to normal

## Types of changes

- [x] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by PurpShell** [comment]
See, we'd rather not have to update puppeteer.. We've rejected the idea to update multiple times before. Though this time it seems as though we aren't able to proceed without updating. Can I get your thoughts @pedroslopez on this matter?

**Comment by RC047** [comment]
Yes, because the version of `puppeteer` 13.0.0 is no longer supported for the current version of nodejs

**Comment by tuyuribr** [comment]
Maybe we drop node v12 + (I don't like this, but maybe we need it), ando upgrade puppeteer to 14.4.1 [1]

It's worth noting that:
Ubuntu jammy (22.04LTS) apt install nodejs resolves to node 12.22.9 [2]
Ubuntu kinetic (22.10) apt install nodejs resolves to node 18.7.0 [3]

So we have  a little dilema here : /

Also, if we change pup version we should make a tutorial about how to upgrade to node 18



[1] https://github.com/puppeteer/puppeteer/releases/tag/v14.4.1
[2] https://packages.ubuntu.com/jammy/nodejs
[3] https://packages.ubuntu.com/kinetic/nodejs

**Comment by yaser-f** [comment]
I am experiencing some issues related to puppeteer being outdated. I hope this gets merged soon.

**Pull request closed without merging**
