### PR TITLE
fix: sendMessage with quoted message id

### LINKED ISSUE #3245: message.delete() is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am able to do all other actions successfully but message.delete() is not reflecting anything while it is not even throwing it. It is even able to find the same message when I re-run the script.

### Expected behavior

Delete the actual message (for me)

### Steps to Reproduce the Bug or Issue

Run a simple snippet, scan qr code and all. Now send the 'TEST MESSAGE' text to your phone. It won't get deleted on the phone or other whatsapp web. 
Also applies when I do the same deletion with message after searchMessages or chat.fetchMessages.

### Relevant Code

Some simple code to test this:
```js
client.on('message_create', async (message) => {
    try {
        if (message.body === 'TEST MESSAGE') {
            await message.delete();
            await message.reply('Thanks for message, let me come back soon');
        }
    } catch (error) {
        console.error('An error occurred:', error);
    }
});
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Mac
iOS
^1.25.0
2.3000.1015762919
v22.6.0

### Additional context

_No response_

### LINKED ISSUE #3259: sendMessage with quote will raise an exception
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there,

Sending a message with a `quotedMessageId` will result in the following exception:
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')
    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:54:67)
    at pptr://__puppeteer_evaluation_script__:10:45
    at ExecutionContext._ExecutionContext_evaluate (/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async Client.sendMessage (/node_modules/whatsapp-web.js/src/Client.js:947:28)
```
  
  
Caused by (/src/util/injected/Utils.js)

https://github.com/pedroslopez/whatsapp-web.js/blob/066d8fa75ebc13b9cc74cfcd18ffd847b79be998/src/util/Injected/Utils.js#L45-L58

### Expected behavior

N/A

### Steps to Reproduce the Bug or Issue

1. Send a message using `client.sendMessage()` with a valid `quotedMessageId` in the `MessageSendOptions` object.

### Relevant Code

```client.sendMessage(chatId, body, { quotedMessageId: "false_3XXXXXXXXXX@c.us_3ACXXXXXXXXXXXXXXX98" });```

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

- OS: macOS Sonoma 14.3.1
- Phone OS: iOS 15.x
- whatsapp-web.js version: 1.25.0
- WhatsApp Web version: 2.3000.1016069290
- Node.js Version: 18.17.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alwinlubbers**
Now using `window.Store.Msg.getMessagesById` instead of `window.Store.Msg.get`

# PR Details
This PR fixes the exception that was thrown when using `client.sendMessage()` with a `quotedMessageId` in the `MessageSendOptions` parameter.

## Description
It seemed like `window.Store.get()` couldn't get a message, even with a valid serialized chat message id.

The `window.Store.Msg.getMessagesById` function was taken from here:
https://github.com/pedroslopez/whatsapp-web.js/blob/066d8fa75ebc13b9cc74cfcd18ffd847b79be998/src/Client.js#L1039

## Related Issue
closes #3259

## Motivation and Context
This will solve the problem of being unable to send messages with a quote attached. 

## How Has This Been Tested

I've tested this version with my local Node.js install (system/os details can be found in the mentioned issue).

I've tried sending a couple of messages in private and group chats. With both messages from me and others. It has also been tested on a clean install (without auth).

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by shirser121 — APPROVED** [review]
Good job

**Comment by harryqt** [comment]
I need this fix, @pedroslopez please review.

**Review by BothimTV — APPROVED** [review]

**Review by Jlam9 — APPROVED** [review]

**Review by Jlam9 — APPROVED** [review]
nice

**Comment by arturhc** [comment]
Hi there! Just checking in, do you have any idea when this PR might be merged?

**Comment by shirser121** [comment]
@alechkos @tuyuribr @tuyuribr3 you should approve this

**Review by alechkos — APPROVED** [review]

**Pull request merged**
