### PR TITLE
fix: Contact

### LINKED ISSUE #2299: Block Contact Error: Cannot read properties of undefined (reading 'isMyContact')
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm currently implementing a spam mechanism with my bot. I have a method that evaluates certain parameters, and if I detect spam, I want to block the user. However, when I try to do so, I encounter the following error: "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isMyContact')". Here's the code I'm using:

### Expected behavior

I expected the contact to be blocked but i have the following error:
image

### Steps to Reproduce the Bug or Issue

1. Get the chat
2. Get the contact
3. Use the contact.block() method
image

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

whatsapp-web.js  versión: 1.21.0

### Additional context

_No response_

### LINKED ISSUE #2312: Method client.getContacts() returns invalid Contact objects. New WA version ?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The objects returned are set with `undefined` in almost all properties.

```
PrivateContact {
  id: {
    server: 'g.us',
    user: '<removed>',
    _serialized: '<removed>@g.us'
  },
  number: undefined,
  isBusiness: false,
  isEnterprise: false,
  labels: undefined,
  name: 'aa',
  pushname: undefined,
  sectionHeader: undefined,
  shortName: undefined,
  statusMute: undefined,
  type: 'in',
  verifiedLevel: undefined,
  verifiedName: undefined,
  isMe: undefined,
  isUser: undefined,
  isGroup: undefined,
  isWAContact: undefined,
  isMyContact: undefined,
  isBlocked: false
},
PrivateContact {
  id: {
    server: 'c.us',
    user: '<removed>',
    _serialized: '<removed>@c.us'
  },
  number: undefined,
  isBusiness: false,
  isEnterprise: false,
  labels: undefined,
  name: 'Adrian',
  pushname: 'Adrian',
  sectionHeader: undefined,
  shortName: 'Adrian',
  statusMute: undefined,
  type: 'in',
  verifiedLevel: undefined,
  verifiedName: undefined,
  isMe: undefined,
  isUser: undefined,
  isGroup: undefined,
  isWAContact: undefined,
  isMyContact: undefined,
  isBlocked: false
}
```

### Expected behavior

`number` should be set with a valid value for non group contacts.
`isGroup` should be set with `true` value for group contacts.
 

### Steps to Reproduce the Bug or Issue

1. const contacts = await this.client.getContacts();
2. console.log(contacts);

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Mac
whatsapp-web.js version: 1.21.0
WhatsAppWeb version: 2.2327.4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

### - [How Has the PR Been Tested](#tests)
- [**The environment the PR was tested on**](#env)
- [**I want to test this PR**](#pr-testing)
- [**I have an issue while testing this PR**](#pr-testing-issue)

### - [Types of Changes](#types-of-changes)

---

## Description <a href="#description" id="description"/>
1. Fixes for `Contact` class:
- `Client.getContactById()` method now retreives the valid contact info
- `Contact.block()` method fixed to block a contact
- The value of `Contact.isBlocked` property changes after the `block()` or `unblock()` methods are called

2. Added [inner function](https://github.com/alechkos/whatsapp-web.js/blob/79255811edeb0a7f4b7aaab914ef061cf0b6e361/src/util/Injected.js#L797) to compare between two WWeb versions.
Its purpose is to provide a compatibility between old code implementations and a new updates made for the library to be synced with the newer WWeb versions. The thing will ensure the stable work for WWebJS no matter what version of WWeb is used.

## Motivation and Context <a href="#motivation-and-context" id="motivation-and-context"/>
After the WWeb v2.2327.4 the contact data structure has been modified causing some of the `Contact` class field values to be `undefined`, so it would be nice to fix an issue and keep this lib up-to-date with the latest WWeb version.

## Related Issues <a href="#related-issues" id="related-issues"/>
PR fixes #2299 fixes #2312

## How Has This Been Tested <a href="#tests" id="tests"/>
The code used in tests:

```js
client.on('message', async (message) => {
    if (message.body === '!test') {
        const contact = await client.getContactById(message.author ?? message.from);
        console.log(contact);
        console.log('TRYING TO BLOCK...');
        await contact.block();
        console.log(`CHECKING IF BLOCKED...\n${contact.isBlocked}`);
        console.log('TRYING TO UNBLOCK...');
        await contact.unblock();
        console.log(`CHECKING IF UNBLOCKED...\n${contact.isBlocked}`);
    }
});
```

<details><summary>

### Tested On <a href="#env" id="env"/>
</summary>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS v1.21.0
    - WWeb v2.2327.4
    - Node v16.17.1
    - Chrome 114.0.5735.199
</details>

### To test this PR by yourself you can run one of the following commands: <a href="#pr-testing" id="pr-testing"/>
```powershell
# NPM
npm install github:alechkos/whatsapp-web.js#fix-contact
# YARN
yarn add github:alechkos/whatsapp-web.js#fix-contact
```

### If you encounter any issues while testing this PR, please provide in a comment: <a href="#pr-testing-issue" id="pr-testing-issue"/>
1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWwebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got

## Types of Changes <a href="#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by T3uZ** [comment]
Boa noite, funcionou perfeitamente aqui, obrigado.

**Comment by ivanzigoni** [comment]
hi.
just tested the pr and it seems to be working fine, although some contact's fields (labels, sectionHeader, statusMute, verifiedLevel and verifiedName) are still undefined, since i don't know exactly what they refer to, i guess that's just how it is?

**Comment by PedroLGaldino** [comment]
It still returns the contact as undefined, when sending the contact to another contact and saving it in the mysql database, it worked perfectly before.

**Comment by alechkos** [comment]
> It still returns the contact as undefined, when sending the contact to another contact and saving it in the mysql database, it worked perfectly before.

Provide the code you used

**Comment by PedroLGaldino** [comment]
> 

client.on('message', async msg => {
  const userId = msg.from;
  console.log('Mensagem:', userId, 'Texto:', msg.body);

  const isStatusMessage = msg.from.endsWith('@broadcast');

  if (isStatusMessage) {
    return; // Ignora mensagens de status
  }

  if (ignoredNumbers.includes(userId)) {
    return;
  }
  
  if (!userStates[userId]) {
    let keywordMatched = false;
    for (const keyword of Object.keys(KeywordIntents)) {
      if (msg.body.toLowerCase().includes(keyword.toLowerCase())) {
        const contatoLoja = KeywordIntents[keyword];
        const telefoneLoja = `55${contatoLoja}@c.us`;
        
        
        await sleepRandom();
        client.sendMessage(userId, `Oi tudo bem? Notamos seu interesse no produto da loja ${keyword}.\n\nPara mais informações sobre esse produto entre em contato diretamente com a loja.\n\n${keyword}📱${contatoLoja}`);
    
        
        const contact = await client.getContactById(msg.author ?? userId);
        let nomeCliente = contact.name || contact.pushname;
        const numeroCliente = contact.number;

        const mensagemLoja = `Um cliente demonstrou interesse na loja através de um de nosso anúncios \n\nNome: ${nomeCliente}\nTelefone:${numeroCliente}\n\nÓtima venda! Manda um joinha aqui pra gente confirmando recebimento!`;


        const clienteData = {
          nome: nomeCliente,
          telefone: numeroCliente,
          loja: keyword, // Armazena a loja selecionada no objeto clienteData
          data: new Date()
        };
        insertData('clientes', clienteData);

        const anuncioData = {
          nome: nomeCliente,
          telefone: numeroCliente,
          loja: keyword, // Armazena a loja selecionada no objeto anuncioData
          data: new Date()
        };
        insertData('anuncio', anuncioData);
        
  
        
    
        await sleepRandom();
        client.sendMessage(telefoneLoja, mensagemLoja);
    
        userStates[userId] = 0;
        restartTimeout(userId);
    
        keywordMatched = true;
        break;
      }
    }
  
if (!keywordMatched) {
    // Se não acionar o keywordintents, enviar o menu
await sleepRandom();
client.sendMessage(userId, 'Olá, tudo bem? Selecione a opção de sua preferência.\n\n*1* Solicite o contato com uma de nossas lojas para mais informações por aqui.\n*2* Endereços e horários de nossas unidades.\n*3* Outros');

// Salvar os dados na tabela "Menu"
const contato = await msg.getContact();
const nomeCliente = contato.name || contato.pushname;
const numeroCliente = contato.number;


const menuData = {
  nome: nomeCliente,
  telefone: numeroCliente,
  data: new Date()
  
};
insertData('Menu', menuData);

userStates[userId] = 1;
restartTimeout(userId);
return;


}

**Comment by alechkos** [comment]
@PedroLGaldino 
what wweb version do you use?
```js
console.log(await client.getWWebVersion());
```
did you run `npm install github:alechkos/whatsapp-web.js#fix-contact`?

**Comment by PedroLGaldino** [comment]
> @PedroLGaldino qual versão do wweb vc usa?
> 
> ```js
> console.log(await client.getWWebVersion());
> ```
> 
> você correu `npm install github:alechkos/whatsapp-web.js#fix-contact`?

Yes:

{
  "dependencies": {
    "mysql2": "^3.4.3",
    "qrcode-terminal": "^0.12.0",
    "whatsapp-web.js": "github:alechkos/whatsapp-web.js"
  }
}

**Comment by alechkos** [comment]
@PedroLGaldino 
Can you run
```js
console.log(await client.getWWebVersion());
console.log(await client.getContactById(/** number@c.us */);
```
and send the output without sensitive information?

**Comment by PedroLGaldino** [comment]
> ```js
> console.log(await client.getWWebVersion());
> console.log(await client.getContactById(/** number@c.us */);
> ```

PrivateContact {
  id: {
    server: 'c.us',
    user: 'x',xxxxxxxxxxxxx
    _serialized: xxxxxxxxxxx@c.us'
  },
  number: undefined,
  isBusiness: undefined,
  isEnterprise: undefined,
  labels: undefined,
  name: undefined,
  pushname: 'Client',
  sectionHeader: undefined,
  shortName: undefined,
  statusMute: undefined,
  type: 'in',
  verifiedLevel: undefined,
  verifiedName: undefined,
  isMe: undefined,
  isUser: undefined,
  isGroup: undefined,
  isWAContact: undefined,
  isMyContact: undefined,
  isBlocked: false
}

**Comment by alechkos** [comment]
@PedroLGaldino what about this?
```js
console.log(await client.getWWebVersion());
```

**Comment by PedroLGaldino** [comment]
> @PedroLGaldinoe quanto a isso?
> 
> ```js
> console.log(await client.getWWebVersion());
> ```

Sorry 2.2327.4

**Comment by alechkos** [comment]
@PedroLGaldino 
> 2.2327.4

Is it a buisiness contact? Because i havent checked the fix on buisiness contacts yet

**Comment by PedroLGaldino** [comment]
> @PedroLGaldino
> 
> > 2.2327.4
> 
> Is it a buisiness contact? Because i havent checked the fix on buisiness contacts yet

Yes its a bussines acount and bussines contact. So I'll wait for the solution, if you need help I'm available

**Comment by alechkos** [comment]
@PedroLGaldino 
> Yes its a bussines acount and bussines contact. So I'll wait for the solution, if you need help I'm available

Thank you for your tests, ill chek later and make required changes

**Comment by alechkos** [comment]
@PedroLGaldino I made some checks and this is an object i got after running the command:
```js
console.log(await client.getContactById(/** number@c.us */));
```
```js
BusinessContact {
  businessProfile: {
    id: {
      server: 'c.us',
      user: 'XXXXXXXXXX',
      _serialized: 'XXXXXXXXXX@c.us'
    }
  },
  id: {
    server: 'c.us',
    user: 'XXXXXXXXXX',
    _serialized: 'XXXXXXXXXX@c.us'
  },
  number: 'XXXXXXXXXX',
  isBusiness: true,
  isEnterprise: false,
  labels: undefined,
  name: 'YYYYYYYYYY',
  pushname: 'ZZZZZ',
  sectionHeader: undefined,
  shortName: 'YYYYY',
  statusMute: undefined,
  type: 'in',
  verifiedLevel: 0,
  verifiedName: undefined,
  isMe: false,
  isUser: true,
  isGroup: false,
  isWAContact: true,
  isMyContact: true,
  isBlocked: false
}
```

**Comment by alechkos** [comment]
@PedroLGaldino i made some changes so you can test it, please let me know if you have issues

**Comment by PedroLGaldino** [comment]
> @PedroLGaldino
> 
> > Yes its a bussines acount and bussines contact. So I'll wait for the solution, if you need help I'm available
> 
> Thank you for your tests, ill check later and make required changes

My code is working fine now. I can send the customer's contact to the responsible attendant, saving it in the database perfectly.


Message: 5521967342668@c.us Text: Hello1456
2.2327.4
PrivateContact {
  id: {
    server: 'c.us',
    user: 'xxxxxxxxxxxxxxxxxx',
    _serialized: 'xxxxxxxxxxxxxxxx@c.us'
  },
  number: undefined,
  isBusiness: false,
  isEnterprise: false,
  labels: [],
  name: 'Pedro Jovem ',
  pushname: 'Pedro Galdino',
  sectionHeader: undefined,
  shortName: 'Pedro',
  statusMute: undefined,
  type: 'in',
  verifiedLevel: undefined,
  verifiedName: undefined,
  isMe: undefined,
  isUser: undefined,
  isGroup: undefined,
  isWAContact: undefined,
  isMyContact: undefined,
  isBlocked: false
}
Received a greeting message.

**Comment by ivanzigoni** [comment]
I've tested as well and got less fields as undefined. Imho changing those to null or even boolean values would make it way easier to debug future situations. Does that makes sense?

my return:

BusinessContact {
  businessProfile: {
    id: {
      server: 'c.us',
      user: 'xxxxxxxxxxxx',
      _serialized: 'xxxxxxxxxxxxx@c.us'
    }
  },
  id: {
    server: 'c.us',
    user: 'xxxxxxxxxxxxx',
    _serialized: 'xxxxxxxxxxx@c.us'
  },
  number: 'xxxxxxxxxxxxx',
  isBusiness: true,
  isEnterprise: false,
  labels: undefined,
  name: 'Xxxx xxx',
  pushname: undefined,
  sectionHeader: undefined,
  shortName: 'Xxx',
  statusMute: undefined,
  type: 'in',
  verifiedLevel: 0,
  verifiedName: 'Xxx Xxx',
  isMe: false,
  isUser: true,
  isGroup: false,
  isWAContact: true,
  isMyContact: true,
  isBlocked: false
}
is blocked  true

(also tested blocking, and it is working fine)

**Comment by alechkos** [comment]
@ivanzigoni 
> I've tested as well and got less fields as undefined. Imho changing those to null or even boolean values would make it way easier to debug future situations. Does that makes sense?

I think that won't be a good idea to change those undefined fields to boolean since not all their values are supposed to be boolean

**Review by Matheus-Lima-Moreira — APPROVED** [review]
Just worked fine for me, i had some issues recently with wwebjs that multiplied some groups generating a new group with a new id, this group was recognized as a contact and received the new messages, while the old one only sent, after this patch the problem is fixed.
wwebjs version test was 1.21 and 1.95

**Comment by diegofemello** [comment]
worked for me, thanks

**Review by diegofemello — APPROVED** [review]

**Comment by hldpzz** [comment]
Worked here, thank you very much!

**Review by pedroherpeto — APPROVED** [review]

**Comment by fenchai23** [comment]
bro where is the merge🤨

**Review by Matheus-Lima-Moreira — APPROVED** [review]

**Comment by T3uZ** [comment]
Mais alguem com problemas para baixar no ??
npm install github:alechkos/whatsapp-web.js#fix-contact

**Review by toooong — APPROVED** [review]

**Review by soluque — APPROVED** [review]

**Review by T3uZ — APPROVED** [review]

**Comment by Mr-Nobody1** [comment]
worked for me

**Comment by Mr-Nobody1** [comment]
works fine on my machine but when I try to do it on VM it shows me this
image

**Comment by alechkos** [comment]
@Mr-Nobody1 
> when I try to do it on VM it shows me this

The error you got is unrelated to this PR, check your git settings on the VM

**Comment by Mr-Nobody1** [comment]
> @Mr-Nobody1
> 
> > when I try to do it on VM it shows me this
> 
> The error you got is unrelated to this PR, check your git/npm settings on the VM

Ok I was able to install it and it works fine. Thanks

**Review by tuyuribr — APPROVED** [review]

**Comment by shirser121** [comment]
@pedroslopez @PurpShell

**Review by shirser121 — APPROVED** [review]
LGTM

**Pull request merged**
