### PR TITLE
Added events which are fired when deleting messages && Added Contact Support similar to PrivateChat and GroupChat

### PR DESCRIPTION
**Pull request by aliyss**
- check the example.js for examples on how to use it
- message_revoke_everyone: is fired when the message is deleted for everyone.
- message_revoke_me: is fired when the message is deleted from the clients view.

### CODE REVIEW

**Comment by pedroslopez** [comment]
Hey! Thanks for contributing. I've now been able to test this, and it seems only the MESSAGE_REVOKE_ME event is being triggered. I am unable to reproduce the `everyone` variant.

Following the same line, maybe a more generalized message deleted event would also be good to have.

**Comment by Aliyss** [comment]
> Hey! Thanks for contributing. I've now been able to test this, and it seems only the MESSAGE_REVOKE_ME event is being triggered. I am unable to reproduce the `everyone` variant.

Fixed it now... should work now.

**Comment by Aliyss** [comment]
@pedroslopez should work now.

**Comment by Aliyss** [comment]
Its alright will post the updated version tomorrow as a new git pull

**Comment by pedroslopez** [comment]
This looks really good and I’d like to get this merged. However, there’s a lot here. Can you please separate this into a couple PRs based on feature? Like have one PR for the Contacts feature, another for the delete events, another for mentions, etc. Thanks!

**Comment by Aliyss** [comment]
Yes ofc. I totally forgot. Will do. Thanks for noticing.

**Comment by Aliyss** [comment]
Finished with the other PRs

**Pull request closed without merging**
