### PR TITLE
feat: send polls

### PR DESCRIPTION
**Pull request by alechkos**
# Table of Contents <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#toc" id="toc"/>

### - [How Has the PR Been Tested (latest test on 19.10.2023)](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#tests)
- [**The environment the PR was tested on**](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#env)
- [**I have an issue while testing this PR**](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#pr-testing-issue)

### - [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#types-of-changes)

---

## Description [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#description" id="description"/>
The PR adds functionality to create and send polls.
In order to send a poll you should add a minimum of 2 poll options and a maximum of 12, otherwise the message simply won't be sent.

Created a new `Poll` class that takes three parameters:
1. The name of a poll as a string
2. Poll options as an array of strings
3. Additional `options` object with properties:
    1. `allowMultipleAnswers`:
        - if false: a single choice poll will be created **(false by default)**
        - if true: a multiple choice poll will be created
    2. `messageSecret` property can be used as a poll ID, it presents a custom array of **32** numbers, that array will be converted to `Uint8Array` inside the browser context
        > [!NOTE]
        > It has to be a unique vector

**A Single Choice Poll** | **A Multiple Choice Poll**
:-----------------------:|:-------------------------:
  |  

## Motivation and Context <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#motivation-and-context" id="motivation-and-context"/>
I noticed that many people asked for the functionality of creating and sending polls, so I thought it would be a good idea to implement it.

## Usage Example [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#usage-example" id="usage-example"/>

```js
client.on('message', async (msg) => {
    if (msg.body === '!sendpoll') {
        /** By default the poll is created as a single choice poll: */
        const pollMsg = await msg.reply(new Poll('Winter or Summer?', ['Winter', 'Summer']));

        /**
         * The example of the poll message structure:
         * 
         * {
         *  _data: {
         *    id: {
         *      fromMe: true,
         *      remote: {
         *        server: 'g.us',
         *        user: 'XXXXXXXXXX',
         *        _serialized: 'XXXXXXXXXX@g.us'
         *      },
         *      id: '3EB01BCC4ACBC48A7A291F',
         *      participant: {
         *        server: 'c.us',
         *        user: 'XXXXXXXXXX',
         *        _serialized: 'XXXXXXXXXX@c.us'
         *      },
         *      _serialized: 'true_XXXXXXXXXX@g.us_XXXXXXXXXXXXXXXXXXXX_XXXXXXXXXX@c.us'
         *    },
         *    viewed: false,
         *    body: '',
         *    type: 'poll_creation',
         *    t: 1697720947,
         *    from: {
         *      server: 'c.us',
         *      user: 'XXXXXXXXXX',
         *      _serialized: 'XXXXXXXXXX@c.us'
         *    },
         *    to: {
         *      server: 'g.us',
         *      user: 'XXXXXXXXXX',
         *      _serialized: 'XXXXXXXXXX@g.us'
         *    },
         *    self: 'out',
         *    ack: 0,
         *    isNewMsg: true,
         *    star: false,
         *    kicNotified: false,
         *    isFromTemplate: false,
         *    latestEditMsgKey: null,
         *    latestEditSenderTimestampMs: null,
         *    mentionedJidList: [],
         *    groupMentions: [],
         *    isVcardOverMmsDocument: false,
         *    isForwarded: false,
         *    hasReaction: false,
         *    messageSecret: {
         *      '0': 206,
         *      '1': 107,
         *      '2': 188,
         *      '3': 169,
         *      '4': 137,
         *      '5': 132,
         *      '6': 8,
         *      '7': 66,
         *      '8': 108,
         *      '9': 31,
         *      '10': 146,
         *      '11': 161,
         *      '12': 211,
         *      '13': 144,
         *      '14': 244,
         *      '15': 190,
         *      '16': 11,
         *      '17': 16,
         *      '18': 228,
         *      '19': 117,
         *      '20': 225,
         *      '21': 191,
         *      '22': 114,
         *      '23': 72,
         *      '24': 126,
         *      '25': 171,
         *      '26': 222,
         *      '27': 53,
         *      '28': 46,
         *      '29': 236,
         *      '30': 168,
         *      '31': 243
         *    },
         *    productHeaderImageRejected: false,
         *    lastPlaybackProgress: 0,
         *    isDynamicReplyButtonsMsg: false,
         *    isMdHistoryMsg: false,
         *    stickerSentTs: 0,
         *    isAvatar: false,
         *    lastUpdateFromServerTs: 0,
         *    invokedBotWid: null,
         *    bizBotType: null,
         *    botResponseTargetId: null,
         *    botPluginType: null,
         *    botPluginReferenceIndex: null,
         *    botPluginSearchProvider: null,
         *    botPluginSearchUrl: null,
         *    requiresDirectConnection: null
         *  },
         *  mediaKey: undefined,
         *  id: {
         *    fromMe: true,
         *    remote: {
         *      server: 'g.us',
         *      user: 'XXXXXXXXXX',
         *      _serialized: 'XXXXXXXXXX@g.us'
         *    },
         *    id: 'XXXXXXXXXX',
         *    participant: {
         *      server: 'c.us',
         *      user: 'XXXXXXXXXX',
         *      _serialized: 'XXXXXXXXXX@c.us'
         *    },
         *    _serialized: 'true_XXXXXXXXXX@g.us_XXXXXXXXXXXXXXXXXXXX_XXXXXXXXXX@c.us'
         *  },
         *  ack: 0,
         *  hasMedia: false,
         *  body: 'Cats or Dogs?',
         *  type: 'poll_creation',
         *  timestamp: 1697720947,
         *  from: 'XXXXXXXXXX@c.us',
         *  to: 'XXXXXXXXXX@g.us',
         *  author: undefined,
         *  deviceType: 'android',
         *  isForwarded: false,
         *  forwardingScore: 0,
         *  isStatus: false,
         *  isStarred: false,
         *  broadcast: undefined,
         *  fromMe: true,
         *  hasQuotedMsg: false,
         *  hasReaction: false,
         *  duration: undefined,
         *  location: undefined,
         *  vCards: [],
         *  inviteV4: undefined,
         *  mentionedIds: [],
         *  orderId: undefined,
         *  token: undefined,
         *  isGif: false,
         *  isEphemeral: undefined,
         *  links: undefined,
         *  pollName: 'Cats or Dogs?',
         *  pollOptions: [ { name: 'Cats', localId: 0 }, { name: 'Dogs', localId: 1 } ],
         *  allowMultipleAnswers: false,
         *  pollInvalidated: false,
         *  isSentCagPollCreation: false
         * }
         */
        console.log(pollMsg);

        /** If you want to provide a multiple choice poll, add allowMultipleAnswers as true: */
        await msg.reply(new Poll('Cats or Dogs?', ['Cats', 'Dogs'], { allowMultipleAnswers: true }));

        /**
         * You can provide a custom message secret, it can be used as a poll ID:
         * @note It has to be a unique vector with a length of 32
         */
        await msg.reply(
            new Poll('Cats or Dogs?', ['Cats', 'Dogs'], {
                messageSecret: [
                    1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]
            })
        );
    }
});
```

## To test this PR by yourself you can run one of the following commands: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#add-polls
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#add-polls
```

## How Has This Been Tested (latest test on 19.10.2023) [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#tests" id="tests"/>
Was tested with a code provided in usage example.

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS **v1.22.2-alpha.3**
    - WWeb **v2.2333.11**, **v2.2344.53**
    - Puppeteer **v18.2.1**
    - Node **v18.17.1**
    - Chrome **v118.0.5993.71**

---

### If you encounter any issues while testing this PR, please provide in a comment (click to expand): <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#pr-testing-issue" id="pr-testing-issue"/>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWWebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got

> [!IMPORTANT]
> **You have to [reapply](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#pr-testing) the PR each time it is changed (new commits were pushed since your last application)**

---

## Types of Changes [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2377#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [X] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

### CODE REVIEW

**Comment by shirser121** [comment]
What is the difference from #1887 ?

**Comment by alechkos** [comment]
@shirser121 
> What is the difference from #1887 ?

The #1887 implements the `PollVote` (the vote of the poll) by adding this functionality:
1. Listener for poll receiving
2. Viewing others' votes
3. The ability to vote

This PR extends the #1887 by adding the ability to create and send votes

**Comment by CSFelix** [comment]
Tested on Windows with an Android Multidevice and it worked!!!

**Comment by digitalsolitario** [comment]
i am not able to get response. when some one click on option.

**Comment by alechkos** [comment]
@digitalsolitario 
> i am not able to get response. when some one click on option.

I will check soon

**Comment by alechkos** [comment]
@digitalsolitario 
> i am not able to get response. when some one click on option.

I have just separated this PR from the #1887, this PR is for sending polls, so if you want to receive a response when someone votes, you should apply #1887

**Comment by diegofemello** [comment]
> @digitalsolitario
> 
> > i am not able to get response. when some one click on option.
> 
> I have just separated this PR from the #1887, this PR is for sending polls, so if you want to receive a response when someone votes, you should apply #1887

many merge conflicts between these two branches, and resolving the conflicts, broke the functionality, preventing the sending of polls...
it would be cool if it was on this branch

**Comment by alechkos** [comment]
@diegofemello 
> Many merge conflicts between these two branches, and resolving the conflicts, broke the functionality, preventing the sending of polls...

I will make compatibility changes as soon as the #1887 is up-to-date, working, approved, and merged. Until then, these are two separate PRs.

**Comment by digitalsolitario** [comment]
Any update regarding poll response.

**Comment by alechkos** [comment]
@digitalsolitario 
> Any update regarding poll response.

Please read the pr [description](https://github.com/pedroslopez/whatsapp-web.js/pull/2377#description) properly, this pr doesn't cover the poll response

**Comment by iamvinny** [comment]
+1

**Comment by digitalsolitario** [comment]
When i am trying too install This :  npm install github:alechkos/whatsapp-web.js#add-polls

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/alechkos/whatsapp-web.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-23T09_53_00_971Z-debug.log
[root@localhost node]# npm i github:alechkos/whatsapp-web.js#add-polls
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/alechkos/whatsapp-web.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-23T09_54_47_928Z-debug.log

**Comment by alechkos** [comment]
@digitalsolitario 
The error you got is not related to this pr

**Comment by diegofemello** [comment]
up

**Review by RC047 — APPROVED** [review]

**Comment by lfamorim** [comment]
Please, integrate this PR.

**Comment by 16Jorgecamargo** [comment]
Is there any chance of putting a custom ID in each poll option? for example, on the buttons there were name options, ID on each button and when the button was clicked it performed an action based on the ID.

**Comment by alechkos** [comment]
@16Jorgecamargo 
> Is there any chance of putting a custom ID in each poll option?

You are always free to modify the code as you want :) but im not planning to add custom ids to poll options in this pr

**Comment by tuyuribr** [comment]
Tested, good as usual! But we need the event on poll vote!

**Review by tuyuribr — APPROVED** [review]

**Review by tuyuribr — CHANGES_REQUESTED** [review]
Please allow custom messageSecret. Just check if the setted messageSecret is Uint8Array(32) and comment in the docs that it has to be a unique vector.
I tested here and it works as some sort of id even if you restart the bot (disconnect and 
Screenshot_19
reconnect)

**Comment by tuyuribr** [comment]
> I have that implementation in another branch, do you want me to bring it here?
Let's talk to @PurpShell , for now lets commit without events

> Done, thank you for noticing this option

If you think is valid, lets include something like this in the docs for the messageSecret:
```javascript
      let secret = new Uint8Array(32);
            for(let i =0; i < 32; i++){
                secret[i] =0;
            }
            secret[0] =1;
            secret[1] =2;
            secret[2] =3;
```

**Review by tuyuribr — APPROVED** [review]
Good work

**Review by shirser121 — APPROVED** [review]
Thanks!

**Comment by carpete-americana** [comment]
So i get this error:
`C:\Users\andre\Desktop\ChatBot-Saquarema\node.js:24
    await msg.reply(new Poll("teste", ['Winter', 'Summer']))
                        ^
ReferenceError: Poll is not defined`

What could be the problem?

**Comment by WichyAlonzo** [comment]
> Así que recibo este error: `C:\Users\andre\Desktop\ChatBot-Saquarema\node.js:24 await msg.reply(new Poll("teste", ['Winter', 'Summer'])) ^ ReferenceError: Poll is not defined`
> 
> ¿Cuál podría ser el problema?
const { Client, LocalAuth, Location, MessageMedia, MessageAck, Poll } = require('whatsapp-web.js');
await message.reply(new Poll(encuestaName, encuestaOption, { allowMultipleAnswers: encuestaAll }));

**Pull request merged**
