### PR TITLE
Detect connection error and throw Authentication failed

### PR DESCRIPTION
**Pull request by shirser121**

### CODE REVIEW

**Comment by shirser121** [comment]
fix https://github.com/pedroslopez/whatsapp-web.js/issues/1660

**Review by tuyuribr — APPROVED** [review]

**Review by jtouris — APPROVED** [review]

**Comment by shirser121** [comment]
@PurpShell can you review this PR?

**Comment by PurpShell** [comment]
Hey! Is the selector used SPECIFIC to the session error? "logout button" sounds like the one in the loading screen as well.

**Comment by tuyuribr** [comment]
up

**Pull request closed without merging**
