### PR TITLE
Fixing the queryWidExists function

### PR DESCRIPTION
**Pull request by tofers**
Fixing the queryWidExists function

# PR details

Function fix

## Related Question

https://github.com/pedroslopez/whatsapp-web.js/pull/1987 https://github.com/pedroslopez/whatsapp-web.js/issues/1313 https://github.com/pedroslopez/whatsapp-web.js/issues/1985

## Motivation and Context

Important feature that is responsible for verifying the number on WhatsApp

## How has this been tested

I compared the code of the old function and the new one. I also tested this code to see if it would run on a Linux system

fix package.json
```
"whatsapp-web.js": "github:tofers/whatsapp-web.js#fix-queryWidExists"
```
or npm
```
npm i github:tofers/whatsapp-web.js#fix-queryWidExists

```

## Types of changes

- [ ] Change dependencies
- [x] Bug fix (non-breaking change that fixes the problem)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Violating change (a fix or feature that will change existing functionality)

## Checklist

- [x] My code matches the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tuyuribr** [comment]
Hi, the current ` window.Store.QueryExist = window.mR.findModule('queryWidExists')[0].queryExists;` stoped working for me 100%.

Your solution is working in my tests thanks.

**Review by tuyuribr — APPROVED** [review]

**Review by tuyuribr — CHANGES_REQUESTED** [review]
Tested again in other server, this seems to fail in 
Client.getNumberId
```
Error: Evaluation failed: Error: wid error: invalid wid
    at new c (https://web.whatsapp.com/app.af1c9e40459f98eb9cf6.js:68:45629)
    at Object.s [as createWid] (https://web.whatsapp.com/app.af1c9e40459f98eb9cf6.js:68:50850)
    at __puppeteer_evaluation_script__:2:49
    at ExecutionContext._evaluateInternal (/home/user/zap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/user/zap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/home/user/zap/node_modules/whatsapp-web.js/src/Client.js:1044:16)
    at async Server.<anonymous> (/home/user/zap/main.js:1455:39)

```

**Comment by tofers** [comment]
Я думаю, что не все серверы обновились до последней версии. 

Я добавлю временно решение для поддержки обоих версий

**Comment by tofers** [comment]
> Tested again in other server, this seems to fail in
> Client.getNumberId

I have added support for version 2.2305.7

But I don't think this is good code, probably should wait until WhatsApp is updated for everyone.

**Comment by brayanfarias** [comment]
it seems to solve my problem for now!

**Review by shirser121 — CHANGES_REQUESTED** [review]
I think it's better to change to this.
```js
window.Store.QueryExist = window.mR.findModule((m) => m.queryWidExists || m.queryExists)[0].queryExists;

**Review by tuyuribr — APPROVED** [review]

**Review by EshanJayasinghe-dev — APPROVED** [review]

**Pull request merged**
