### PR TITLE
Handle qrcode canvas timeout

### PR DESCRIPTION
**Pull request by guicuton**
This change handle the timeout from canvas qrcode.
When the user re-paired to an existing instance (client) and the `qrTimeoutMs`it's exceeded the error below is fired:

screen

### CODE REVIEW

**Comment by guicuton** [comment]
I've made a Indentation adjust and new error handle when browser/client is closed while is waiting qrcode scan

**Comment by canove** [comment]
@pedroslopez , can this be merged?

**Comment by MuhShalah007** [comment]
@pedroslopez , can this be merged?

**Comment by faizalmansor** [comment]
This issue happen to me today.  
```
UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
```
But it happen after I scanned the QR code (after some time has passed)

**Comment by MuhShalah007** [comment]
same problem

**Comment by mzhirnov1** [comment]
Same problem here

**Comment by mzhirnov1** [comment]
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded

**Comment by d0v3riz** [comment]
> is issue happen to me

Same problem here

**Comment by stefanfuchs** [comment]
Does this PR solve the problem, or it just improves the error messages?

Also, I am having the same problem here with one specific number only (it's an iPhone).
The other numbers I tested were working fine... I'm trying to figure out what's happening.

**Comment by sostenesapollo** [comment]
what can i do to solve this /

**Comment by ijunaid8989** [comment]
> I resolved this issue by exiting the beta for multiple devices.

can you explain what this means?

**Comment by jrvidotti** [comment]
> > I resolved this issue by exiting the beta for multiple devices.
> 
> can you explain what this means?

Whatsapp releases a beta version for multiple devices (not only Whatsapp Web). I think this project cannot work with this function...

**Comment by RafaelAngelRamirez** [comment]
> > > I resolved this issue by exiting the beta for multiple devices.
> > 
> > 
> > can you explain what this means?
> 
> Whatsapp releases a beta version for multiple devices (not only Whatsapp Web). I think this project cannot work with this feature.
> 
> In my case, multiple devices are turned off but I'm getting this error also.

You need to exit the beta version that is available on mobile, not just log out of the other devices.

**Comment by jrvidotti** [comment]
> > Whatsapp releases a beta version for multiple devices (not only Whatsapp Web). I think this project cannot work with this feature.
> > In my case, multiple devices are turned off but I'm getting this error also.
> 
> You need to exit the beta version that is available on mobile, not just log out of the other devices.

I never opted in this feature in mobile device and is actually turned off.

**Comment by OfirApps** [comment]
Well, what am i supposed to do know when the update is working for everyone?

**Pull request closed without merging**
