### PR TITLE
fix: typescript compilation

### LINKED ISSUE #1648: Cannot build with tsc
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Found 35 errors in 1 files.

Errors  Files
    35  node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/types.d.ts:1238
    
    Few Error lines are as below,
    node_modules/.pnpm/@types+puppeteer@5.4.6/node_modules/@types/puppeteer/index.d.ts:55:46 - error TS2304: Cannot find name 'Element'.

55 export type WrapElementHandle<X> = X extends Element ? ElementHandle<X> : X;
                                                ~~~~~~~

node_modules/.pnpm/@types+puppeteer@5.4.6/node_modules/@types/puppeteer/index.d.ts:89:56 - error TS2304: Cannot find name 'Element'.

89     $eval<R>(selector: string, pageFunction: (element: Element) => R | Promise<R>): Promise<WrapElementHandle<R>>;

On dev nodemon server its working. But cannot build project.
Issue started after cleaning up node_modeules folder and reinstalling packages.
 
    

### Expected behavior

I expect to build the project and compile ts to js.

But typescript compilation error.

I think some type issues with puppeteer@13.7.0

### Steps to Reproduce the Bug or Issue

1. Remove node_modules
2. Reinstall npm packages, (npm i, yarn, pnpm i)
3. Run "tsc" to build the typescript project
4. You will see types error.

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Ubuntu 20
Phone OS: Android
whatsapp-web.js version : 1.17.1
WhatsApp Web version : 2.2230.10
Node.js Version : v18.7.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stefanfuchs**
Fix compilation with TSC.
Fixes #1648

In order to test:

```
npm i -D typescript
npx tsc index.d.ts
```

### CODE REVIEW

**Review by purpshell — APPROVED** [review]

**Comment by Aliyss** [comment]
Bro... Not sure if this works... Like can we just change Store function arguments from session to options? Are those not used anywhere?

**Comment by stefanfuchs** [comment]
The previous syntax was actually incorrect... The function's var name was missing. For example:

`sessionExists: ({session: string}) => Promise...`

Is an incorrect syntax in typescript because the var name for the first parameter, **which is an object containing a 'session' prop**, is missing, and that's why it wouldn't compile.

I just added the var name for the first parameter, which could be anything really, but I chose 'options' because the other methods in the lib are already using this name as well for their parameters.

**Review by aliyss — APPROVED** [review]
gg

**Comment by stefanfuchs** [comment]
The previous syntax was actually incorrect... The function's var name was
missing. For example:

`sessionExists: ({session: string}) => Promise...`

Is an incorrect syntax in typescript because the var name for the first
parameter, **which is an object containing a 'session' prop**, is missing,
and that's why it wouldn't compile.

I just added the var name for the first parameter, which could be anything
really, but I chose 'options' because the other methods in the lib are
already using this name as well for their parameters.

**Pull request merged**
