### PR TITLE
Feat: get message by id

### PR DESCRIPTION
**Pull request by shirser121**
Add the feature of getting messages by id.
Loads messages that are not loaded in the Store.Msg, and add them into the Store.Msg.
I don't use the draft because this is already work

### CODE REVIEW

**Comment by tuyuribr** [comment]
#847

**Comment by tuyuribr** [comment]
We need to test a lot, because #847 was working for a lot of recent messages, but for older msgs it wasn't. I think it is fixed since MD has all msgs but we still need to test it. I'm linking the tests from that PR:
image
(some random fails)

it was failing after 1592863 seconds ( 18 days )

[parcial.csv](https://github.com/pedroslopez/whatsapp-web.js/files/9300775/parcial.csv)

**Comment by shirser121** [comment]
> We need to test a lot, because #847 was working for a lot of recent messages, but for older msgs it wasn't. I think it is fixed since MD has all msgs but we still need to test it. I'm linking the tests from that PR: image (some random fails)
> 
> it was failing after 1592863 seconds ( 18 days )
> 
> [parcial.csv](https://github.com/pedroslopez/whatsapp-web.js/files/9300775/parcial.csv)

This is the way WhatsApp itself get messages from the db

**Comment by shirser121** [comment]
@tuyuribr How should we test it?

**Comment by pedrorenan** [comment]
It works fine for me.

**Comment by tuyuribr** [comment]
@shirser121 , sorry for being late. We should dump the local sqlite db (from a cellphone) and them compare it with the waweb.
But I think we can test just some old messages and call it a day. Oh, don't forget index.d.ts

( I think with index.d.ts we can merge this )

**Comment by chrishubert** [comment]
Can we consider merging this one @pedroslopez ?
That would open a world lot of possibilities 🎉

**Comment by PurpShell** [comment]
This pull request lacks the proper guidelines to be pushed.

1. It lacks testing
2. It lacks type declarations (in index.d.ts)

**Review by codebossdev — APPROVED** [review]

**Review by alechkos — APPROVED** [review]
Works here, thank you!

**Comment by shirser121** [comment]
@tuyuribr @aliyss @pedroslopez @PurpShell 
We should merge this because its super important feature

**Review by tuyuribr — APPROVED** [review]

**Comment by loic-hamdi** [comment]
> it work with me
> 
> the code :
> 
> ```
> client.on('message_reaction', async reaction => {
>   if(reaction.reaction==='❤️'){
>     console.log(reaction.msgId._serialized)
>     let msg = await client.getMessageById(reaction.msgId._serialized);
>     console.log(msg)
>   }
> });
> ```

This is broken when you try to do it on a message sent to yourself

**Pull request merged**
