### PR TITLE
Support for WhatsApp Web 2.2241.6

### LINKED ISSUE #1758: Cannot read properties of undefined (reading 'isMDBackend')
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cannot read properties of undefined (reading 'isMDBackend')

### Expected behavior

to function well

### Steps to Reproduce the Bug or Issue

just run a normal cose 

### Relevant Code

_No response_

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

latest versions 

### Additional context

no more

### PR DESCRIPTION
**Pull request by pedroslopez**
# PR Details

Fixes an issue where isMDBackend seems to be removed

close #1758 supersedes #1760 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by pedroslopez** [comment]
Ideally we should just remove all non-MD things from the lib, but WhatsApp is still serving 2.2240.7 which does have support for it. Once WhatsApp stops serving that version, we should clean things up.

**Review by hilmanyanuar90 — APPROVED** [review]

**Review by hilmanyanuar90 — APPROVED** [review]

**Review by hilmanyanuar90 — APPROVED** [review]

**Review by hilmanyanuar90 — APPROVED** [review]

**Review by hilmanyanuar90 — APPROVED** [review]

**Comment by Tina4545** [comment]
@pedroslopez you just closed this issue but I'm still new its nots clear what exactly I should to to fix this bug

**Comment by pedroslopez** [comment]
> @pedroslopez you just closed this issue but I'm still new its nots clear what exactly I should to to fix this bug 

@Tina4545 You should update the library to v1.18.2 for proper compatibility with the latest WhatsApp web version

**Comment by Srashmi57** [comment]
> > @pedroslopez you just closed this issue but I'm still new its nots clear what exactly I should to to fix this bug
> 
> @Tina4545 You should update the library to v1.18.2 for proper compatibility with the latest WhatsApp web version

@pedroslopez Hi, I am facing the same issue. Will updating the library to v1.18.2 resolve it?

**Comment by areatecnicapm** [comment]
@pedroslopez  updated to  v1.18.2 version and deleting sessions and restarting all... but issue is always there

**Comment by noxtbing** [comment]
Confirmo el problema se soluciono, gracias @pedroslopez por mantener este proyecto.

**Review by 7koma95 — APPROVED** [review]

**Pull request merged**
