### PR TITLE
Hot Fix WA 2.2147.14

### PR DESCRIPTION
**Pull request by tuyuribr**
Not working 100% rn:
QueryExists
getProfilePic (needs a try catch)

### CODE REVIEW

**Comment by ramphy** [comment]
Working. Thank you.

**Comment by eduardoa1ves** [comment]
Working :D

**Comment by tonvital** [comment]
Please, how to put this PR in package.json?
"whatsapp-web.js": "1.15.2"

**Comment by ahmadzakki15** [comment]
Error

any solution ??

**Comment by tuyuribr** [comment]
Not working 100% rn:
QueryExists
SendPresence
getProfilePic (needs a try catch)

**Comment by yoitscarolinee** [comment]
Working, thank you!

**Comment by Erick21** [comment]
Thank you, working :)

**Comment by gg3083** [comment]
Where did you find queryExist?

**Comment by ItsMisa** [comment]
> Thank you, working can send :) but can not run isRegisteredUser

I also encountered the same error when I used isRegisteredUser api.
Error: Evaluation failed: TypeError: window.Store.USyncQuery is not a constructor

**Comment by ItsMisa** [comment]
> 

After testing, it seems that only the mobile phone number that has not registered WhatsApp will report the error

**Review by pedroslopez — APPROVED** [review]

**Comment by makanSukros** [comment]
> > 
> 
> After testing, it seems that only the mobile phone number that has not registered WhatsApp will report the error

I change this function:

from :

async isRegisteredUser(id) {
        return await this.pupPage.evaluate(async (id) => {
            let result = await window.Store.Wap.queryExist(id);
            // console.log('isRegisteredUser result', result);

            return result.jid !== undefined;
        }, id);
}

to 

async isRegisteredUser(id) {
        return await this.pupPage.evaluate(async (id) => {

            const contactWid = window.Store.WidFactory.createWid(id);
            let result = await window.Store.CheckRegisteredOnWhatsApp(contactWid);
            // console.log('isRegisteredUserNew result', result);

            try{
                var reswid = result.wid._serialized;
                return ((reswid !== null) && (typeof reswid !== 'undefined'))
            }catch(ex){
                return false;
            }
            
        }, id);
 }

**Comment by makanSukros** [comment]
And i add this line to injected js

var modulesByCondition = Object.keys(window.mR.modules);
    modulesByCondition.forEach(async function(mKey) {
      mod = window.mR.modules[mKey];
      if (typeof mod !== 'undefined') {
        if(typeof mod.default != 'undefined'){
          try{
            if(mod.default.toString().includes('Should not reach queryExists MD')){
              window.Store.CheckRegisteredOnWhatsApp = mod.default;
            }
          }catch(ex){

          }

        }
      }
    });

**Pull request merged**
