### PR TITLE
Fix for error when send files: Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function

### PR DESCRIPTION
**Pull request by macleysousa**
# PR Details

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by zahmadz** [comment]
Tested here, and it's working. Thanks!

**Comment by ahmadsofuwan** [comment]
how to use, fix bug

**Comment by digitalsolitario** [comment]
Call to Action Button Not working in some Device's Any one have solution.

**Comment by digitalsolitario** [comment]
Injected.js
// window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0];
    window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0];
Thank You It's working.

**Review by Eonus21 — APPROVED** [review]

**Comment by macleysousa** [comment]
> how to use, fix bug

for now i'm using this branch github:macleysousa/whatsapp-web.js

package.json
`
"whatsapp-web.js": "github:macleysousa/whatsapp-web.js"
`

**Comment by Bestfastfire** [comment]
> Injected.js // window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0]; window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0]; Thank You It's working.

Worked here

**Comment by CSFelix** [comment]
Same issue

**Comment by otomay** [comment]
any tips for DownloadManager?

**Comment by janke184** [comment]
Same issue here when trying to send pdf files.


[info] Error Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function
    at Object.window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)
    at async Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)
    at async __puppeteer_evaluation_script__:10:25

**Comment by moussaid521** [comment]
> Injected.js // window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0]; window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0]; Thank You It's working.

that worked fine for me

**Review by gabryelrigol — APPROVED** [review]

**Comment by andresmv94** [comment]
> Injected.js // window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0]; window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0]; Thank You It's working.

yes this is the solution, thanks !!

**Comment by roseniltonreis** [comment]
> > how to use, fix bug
> 
> for now i'm using this branch github:macleysousa/whatsapp-web.js
> 
> package.json `"whatsapp-web.js": "github:macleysousa/whatsapp-web.js"`

This worked for me.

**Review by pedroslopez — APPROVED** [review]
Thanks!

**Comment by K4nishi** [comment]
home/ubuntu/bot-js/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function
    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:293:50)
    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:84:19)
    at async __puppeteer_evaluation_script__:10:25
    at ExecutionContext._evaluateInternal (/home/ubuntu/bot-js/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/ubuntu/bot-js/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (/home/ubuntu/bot-js/node_modules/whatsapp-web.js/src/Client.js:686:28)
    at async Client.<anonymous> (/home/ubuntu/bot-js/botnerfado.js:200:13)



I had a problem, does anyone know how to solve it?

**Pull request merged**
