### PR TITLE
Add search option on chat.fetchMessages by min/max timestamp

### LINKED ISSUE #1547: Add option to fetchMessages | Time period
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like.

fetchMessages using GET MEthod with Time limit

### Describe an alternate solution.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LucianoHanna**

### CODE REVIEW

**Comment by lfdelphino** [comment]
It works here, might need a few exceptions like when max is lower than min or if there is no limit set but seems to be working fine.

**Comment by jurajmatus** [comment]
I would suggest using `break` in case there is a message older than `minTimestamp` (that means that all the messages loaded after will be even older):

```diff
+ if (searchOptions && searchOptions.minTimestamp && loadedMessages.some(msg => msg.t < searchOptions.minTimestamp)) {
+    break
+}
msgs = [...loadedMessages.filter(msgFilter), ...msgs];
```

**Review by purpshell — CHANGES_REQUESTED** [review]
👍 but fix ESLint, will approve after that

**Comment by tuyuribr** [comment]
don't forget index.d.ts too

**Pull request closed without merging**
