### PR TITLE
Fix isOfficialClient

### PR DESCRIPTION
**Pull request by purpshell**
Big thanks to my Sponsors, they allow me to to do work like this. 

[Support my work on GitHub Sponsors](https://github.com/sponsors/PurpShell)

# PR Details

Fixes whatsapp's latest attempt to block us

## Description

We fix the navigator.webdriver property and also the stack error check

## Related Issue

Getting an "unofficial client" warning then logout

## Motivation and Context
Fighting meta lol

## How Has This Been Tested
I tested it myself

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by LaCrak27 — COMMENTED** [review]
Tried to deobfuscate a bit and got nowhere, good job!

**Comment by dannywynn** [comment]
how do we know code is not malicious ?
only a fool would run this on his server.

**Comment by LaCrak27** [comment]
Well he is one of the principal maintainers, in my personal opinion the obfuscation is justified in his case (if it wasn't obfuscated it would probably be insta-patched)

**Review by dannywynn — COMMENTED** [review]
code might be malicious run this on your own risk.

ᵗʳᵘˢᵗ ⁿᵒ ᵒⁿᵉ.

**Comment by PurpShell** [comment]
> code might be malicious run this on your own risk.
> 
> ᵗʳᵘˢᵗ ⁿᵒ ᵒⁿᵉ.

Sure Meta fanboy. This is protected by CORS, what it does is it runs some code in the browser context. If you are so scared you can go ahead and break it apart. I am not doing this because I want to

**Review by DieterKoblenz — APPROVED** [review]
Be cautious when running this, however, reason is justified.

**Comment by dannywynn** [comment]
> Sure Meta fanboy. This is protected by CORS, what it does is it runs some code in the browser context. If you are so scared you can go ahead and break it apart. I am not doing this because I want to

You're acting like a child. Just because I warned people about running this code, you called me a "meta fanboy" lol

**Review by LaCrak27 — APPROVED** [review]
Looks good to me, forgor to approve 💀

**Comment by PurpShell** [comment]
> > Sure Meta fanboy. This is protected by CORS, what it does is it runs some code in the browser context. If you are so scared you can go ahead and break it apart. I am not doing this because I want to
> 
> You're acting like a child. Just because I warned people about running this code, you called me a "meta fanboy" lol

So what? I'm a child! Hahahahha. Seriously though, go argue with someone your age (I'm 16 years of age) and if you want to stay without this patch you can do that as well. 

I ran a poll in the Discord, and the majority accepted this; so I am not going off my own opinion. The other immediate Collaborator, open-wa and wppconnect all will include obfuscation for this patch.. We want it to last as much as possible till 2.3000 (it breaks at that version, since we don't have webpackChunk anymore)

**Comment by dannywynn** [comment]
> I ran a poll in the Discord, and the majority accepted this; so I am not going off my own opinion. The other immediate Collaborator, open-wa and wppconnect all will include obfuscation for this patch.. We want it to last as much as possible till 2.3000 (it breaks at that version, since we don't have webpackChunk anymore)

i am just here to warn, no need to cry.

**Review by dannywynn — APPROVED** [review]
LGTM

**Comment by PurpShell** [comment]
> LGTM

Regarding your concerns, I recognize it's kinda suspicious. I added the first statement (page.evaulateonnewdocument) to show my code will run only in the browser-context. There, you can see your Network requests in the Devtools tab, you can do all you want, the code is running in a safe emulator. Not that anything will happen (CORS policy)

**Review by LaCrak27 — APPROVED** [review]
LGTM2

**Comment by sentinelb51** [comment]
> > Sure Meta fanboy. This is protected by CORS, what it does is it runs some code in the browser context. If you are so scared you can go ahead and break it apart. I am not doing this because I want to
> 
> 
> 
> You're acting like a child. Just because I warned people about running this code, you called me a "meta fanboy" lol 

You say that while downvoting everyone that says anything positive. Stop shoving your own opinion down other peoples' throats

**Comment by PurpShell** [comment]
I just updated the obfuscated portion to use a set seed, and I gave this seed along with the source to the other collaborators. They can now verify this obfuscation to be the same as the source I provided them

**Comment by T3uZ** [comment]
I'll test it, thanks for the contribution

**Comment by herduin** [comment]
Well @PurpShell the ends justify the means! go ahead!

**Review by tuyuribr — CHANGES_REQUESTED** [review]
Sorry bro, I can't Approve this. In theory is a security risk

**Comment by tanu360** [comment]
> > LGTM
> 
> Regarding your concerns, I recognize it's kinda suspicious. I added the first statement (page.evaulateonnewdocument) to show my code will run only in the browser-context. There, you can see your Network requests in the Devtools tab, you can do all you want, the code is running in a safe emulator. Not that anything will happen (CORS policy)

Hi, I attempted to unpack your code. Have a look and let me know If I succeed or not :D

https://gist.github.com/tanu360/f62e03888fb0c7b868e93e790a0e96ec

**Comment by PurpShell** [comment]
Since someone already deobfuscated it, makes less sense to keep it locked

**Comment by vinikjkkj** [comment]
I achieved this by trying to deobfuscate the code from the last commit

const _0x34aa69 = (function () {
    let _0xd6c39a = true
    return function (_0x23efe0, _0x38862e) {
      const _0x3c615d = _0xd6c39a
        ? function () {
            if (_0x38862e) {
              const _0x2e65e9 = _0x38862e.apply(_0x23efe0, arguments)
              return (_0x38862e = null), _0x2e65e9
            }
          }
        : function () {}
      return (_0xd6c39a = false), _0x3c615d
    }
  })(),
  _0x11c472 = _0x34aa69(this, function () {
    return _0x11c472
      .toString()
      .search('(((.+)+)+)+$')
      .toString()
      .constructor(_0x11c472)
      .search('(((.+)+)+)+$')
  })
_0x11c472()
const _0x20d9cc = (function () {
    let _0x10b0b8 = true
    return function (_0x594caf, _0x2b1ab7) {
      const _0x2abd0f = _0x10b0b8
        ? function () {
            if (_0x2b1ab7) {
              const _0x3983d7 = _0x2b1ab7.apply(_0x594caf, arguments)
              return (_0x2b1ab7 = null), _0x3983d7
            }
          }
        : function () {}
      return (_0x10b0b8 = false), _0x2abd0f
    }
  })(),
  _0x2b70da = _0x20d9cc(this, function () {
    let _0x4485c9
    try {
      const _0x52630c = Function(
        'return (function() {}.constructor("return this")( ));'
      )
      _0x4485c9 = _0x52630c()
    } catch (_0x45b935) {
      _0x4485c9 = window
    }
    const _0x204822 = (_0x4485c9.console = _0x4485c9.console || {})
    const _0x3d2660 = [
      'log',
      'warn',
      'info',
      'error',
      'exception',
      'table',
      'trace',
    ]
    for (let _0x2e3588 = 0; _0x2e3588 < _0x3d2660.length; _0x2e3588++) {
      const _0x2eadbe = _0x20d9cc.constructor.prototype.bind(_0x20d9cc),
        _0x42a896 = _0x3d2660[_0x2e3588],
        _0x3b1929 = _0x204822[_0x42a896] || _0x2eadbe
      _0x2eadbe['__proto__'] = _0x20d9cc.bind(_0x20d9cc)
      _0x2eadbe.toString = _0x3b1929.toString.bind(_0x3b1929)
      _0x204822[_0x42a896] = _0x2eadbe
    }
  })
_0x2b70da()
const originalError = Error
Error = function (_0xbcdd4f) {
  const _0x26c6f4 = new originalError(_0xbcdd4f),
    _0x59cf7f = _0x26c6f4.stack
  if (_0x26c6f4.stack.includes('moduleRaid')) {
    _0x26c6f4.stack =
      _0x59cf7f +
      '\n    at https://web.whatsapp.com/vendors~lazy_loaded_low_priority_components.05e98054dbd60f980427.js:2:44'
  }
  return _0x26c6f4
}

**Comment by PurpShell** [comment]
guys it's not a challenge to get it deobfuscated 😆...... This was meant as a way for us to buy more time against meta

**Comment by T3uZ** [comment]
> guys it's not a challenge to get it deobfuscated 😆...... This was meant as a way for us to buy more time against meta

I think it turned into a competition hahaha.
Thank you friend.

**Comment by tanu360** [comment]
> guys it's not a challenge to get it deobfuscated 😆...... This was meant as a way for us to buy more time against meta
> 
> I'm not being aggressive or trying to hide this from you, its just that I thought, why DO THEY get to obfuscate and us NOT?

Sorry My fault. I am removing my gist. I understood your point now. If the code is open then meta will patch it quick and you again have to spend countless hours to find a fix so in order to make the way harder for meta to fix the patch find by you, you applied the obfuscation.

**Comment by PurpShell** [comment]
> > guys it's not a challenge to get it deobfuscated 😆...... This was meant as a way for us to buy more time against meta
> > I'm not being aggressive or trying to hide this from you, its just that I thought, why DO THEY get to obfuscate and us NOT?
> 
> Sorry My fault. I am removing my gist. I understood your point now. If the code is open then meta will patch it quick and you again have to spend countless hours to find a fix so in order to make the way harder for meta to fix the patch find by you, you applied the obfuscation.

Not a problem, the source is now in the code. I talked with a lot of people before making the decision. I know it goes against being open and whatnot.

**Review by tuyuribr — APPROVED** [review]

**Comment by vinikjkkj** [comment]
> pessoal, não é um desafio desofuscá-lo 😆...... Isso foi pensado como uma forma de ganharmos mais tempo contra o meta
> 
> Não estou sendo agressivo nem tentando esconder isso de você, só pensei: por que ELES ofuscam e nós NÃO?

Now only some collaborators who have the seed will be able to view and change the source code?

**Review by alechkos — APPROVED** [review]

**Comment by PurpShell** [comment]
> > pessoal, não é um desafio desofuscá-lo 😆...... Isso foi pensado como uma forma de ganharmos mais tempo contra o meta
> > Não estou sendo agressivo nem tentando esconder isso de você, só pensei: por que ELES ofuscam e nós NÃO?
> 
> Now only some collaborators who have the seed will be able to view and change the source code?
NO LONGER OBFUSCATED, CHECK THE SOURCE.

**Pull request merged**
