### PR TITLE
feat: Optional proxy autentication

### PR DESCRIPTION
**Pull request by puntolino**
# PR Details

I've added the option to optionally autenticate via proxy

## Description

Same as #1949

## Related Issue

https://github.com/pedroslopez/whatsapp-web.js/pull/1949

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by PurpShell** [comment]
Let me make this clear, I don't like when pull requests like this are opened. I'll make an exception since @danielR2001 is inactive and I'd love merge it soon.

CC goes to @danielR2001 and not you :D

**Review by tuyuribr — CHANGES_REQUESTED** [review]
example in examples.js?

**Comment by puntolino** [comment]
Hi @PurpShell of course! 
@tuyuribr I've added the example file (with comments) and detailed better the index.d.ts documentation

**Review by purpshell — APPROVED** [review]
lgtm

**Review by tuyuribr — APPROVED** [review]

**Comment by danielR2001** [comment]
Sorry for being inactive, and thanks for merging!

**Pull request merged**
