### PR TITLE
Fix error in nodejs v12.x

### PR DESCRIPTION
**Pull request by ricardoapaes**
# PR Details

Error running on nodejs 12.x

## Description

Error running on nodejs 12.x

## How Has This Been Tested

Fix tested on my computer and running.

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tuyuribr** [comment]
We should take a look here: #2129

**Comment by ricardoapaes** [comment]
> We should take a look here: #2129

@tuyuribr But the version released yesterday still promises support and unfortunately doesn't.

**Review by shirser121 — APPROVED** [review]
LGTM

**Review by tuyuribr — APPROVED** [review]
TEsted on node 18, worked

**Comment by tuyuribr** [comment]
@ricardoapaes, merge the main branch

**Comment by ricardoapaes** [comment]
Updated

**Comment by ricardoapaes** [comment]
@tuyuribr

**Pull request merged**
