### PR TITLE
update MessageMedia.fromUrl

### PR DESCRIPTION
**Pull request by wictornogueira**
- fromUrl will now set filename based on the url (#808)
- Content-type is now used as fallback

### CODE REVIEW

**Review by purpshell — APPROVED** [review]
lgtm

**Review by tuyuribr — APPROVED** [review]
lgtm

**Comment by tuyuribr** [comment]
Security warning:
`"http://url/file/..\\..\\..\\..\\..\\Windows\\write.exe".split('/').pop();`
Evals to "..\\..\\..\\..\\..\\Windows\\write.exe"
If someone uses MessaMedia.fileName on windows it can break something
But the risk is close to none

**Comment by tuyuribr** [comment]
Warning: if you download something from an empty path ( https://image.somedomain.com/ ) fileName will be empty. but the chances of this happening seems very low

**Review by aliyss — APPROVED** [review]

**Pull request merged**
