### PR TITLE
fix: findImpl

### LINKED ISSUE #2386: Error: Evaluation failed: TypeError: r.findImpl is not a function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue happening when trying to start a session. 

### Expected behavior

This bug not happening, I guess?

### Steps to Reproduce the Bug or Issue

1. Starting some sessions causes this. 

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Ubuntu 22.04

### Additional context

_No response_

### LINKED ISSUE #2387: There is a bug I think it needs an update or whats app did soemthing...happens from time to time
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### Expected behavior

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### Steps to Reproduce the Bug or Issue

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### Relevant Code

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### Additional context

There is a bug I think it needs an update or whats app did soemthing...happens from time to time

### LINKED ISSUE #2388: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to load whatsapp-web.js, it gives me this: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')

### Expected behavior

Just to load whatsapp-web as usual

### Steps to Reproduce the Bug or Issue

Reload whatsapp-web.js

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Linux / Debian
Whatsapp web version: 1.21.0
Nodejs version: v16.15.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

### - [How Has the PR Been Tested](#tests)
- [**The environment the PR was tested on**](#env)
- [**I want to apply this fix**](#pr-testing)

### - [Types of Changes](#types-of-changes)

---

## Description <a href="#description" id="description"/>
From the **WWeb v2.2333.11-beta** the WhatsApp broke some method that caused an issue, this PR fixes the issue.

## Related Issues <a href="#related-issues" id="related-issues"/>
PR closes #2388 closes #2387 fixes #2386

## How Has This Been Tested <a href="#tests" id="tests"/>
Was tested with [`getChatById`](https://docs.wwebjs.dev/Client.html#getChatById), assuming that the current user has never written to the user the method is trying to find.
Works as expected.

<details><summary>

### Tested On <a href="#env" id="env"/>
</summary>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS v1.21.1-alpha.1
    - WWeb v2.2333.11-beta
    - Node v16.17.1
    - Chrome 114.0.5735.199
</details>

### To apply this fix you can run one of the following commands: <a href="#pr-testing" id="pr-testing"/>
```powershell
# NPM
npm install github:alechkos/whatsapp-web.js#fix-findImpl
# YARN
yarn add github:alechkos/whatsapp-web.js#fix-findImpl
```

## Types of Changes <a href="#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tuyuribr** [comment]
To install this fix:
`npm i github:alechkos/whatsapp-web.js#fix-findImpl`

**Review by tuyuribr — APPROVED** [review]

**Review by purpshell — APPROVED** [review]
working

**Comment by produzzasistemas** [comment]
Perfect!

**Comment by MatteoBelvederesi-NewTechnology** [comment]
is not working on business account new chats

**Comment by alechkos** [comment]
@MatteoBelvederesi-NewTechnology 
> is not working on business account

Checked on both personal and business accounts
works as expected

**Comment by VycktorStark** [comment]
The solution broke, it returned to giving the same issue.

**Comment by alechkos** [comment]
@VycktorStark 
> The solution broke, it returned to giving the same issue.

Checked on the latest library version and works as expected. Make sure you are using the latest version

**Comment by VycktorStark** [comment]
> a

The issue occurs with new chats, don't forget that! New chats!

I've found a solution, here it is:
`window.mR.findModule('ChatCollection')[0].ChatCollectionImpl = window.mR.findModule('ChatCollection')[0].ChatCollection`

**Comment by VycktorStark** [comment]
> @VycktorStark
> 
> > The solution broke, it returned to giving the same issue.
> 
> Checked on the latest library version and works as expected. Make sure you are using the latest version

The issue occurs with new chats, don't forget that! New chats!

**Comment by danieligor56** [comment]
that still working ?

**Comment by AGG-an** [comment]
I want to say what I found out, it is normal to send messages to users who have already chatted, but an exception will occur when sending to new users; I tracked the code and found that when you send messages to new users, WhatsApp will go to get **window.mR.findModule(‘ChatCollection’)[0].ChatCollection._find**; only then can you inject and send messages to new users.

**Pull request merged**
