### PR TITLE
Fix buttons list

### PR DESCRIPTION
**Pull request by sergiooak**
I did a hard fork of PR #1639 from @shirser121 because I was not able to fork/commit on his branch...

I have fixed a broken string a fixed style for eslint and added a demo to example.js
---
### Lists:
Working normally
image
image
---
### Buttons
Limiting to two especial buttons (url or phone) and 3 regular buttons works fine
image
Any button more cause a crash on sender and on receiver, so I have added a filter on Buttons.js to limit it.
---
### Know bugs
On the phone of the bot, the buttons appear as if the user (receiver) had sent the message
image
On sender web, receiver phone and web it appears just fine

During tests, when I close and open the bot chromium throws Out of Memory error sometimes when WhatsApp web is organizing messages, don't know if it is relatable.
image

### CODE REVIEW

**Comment by budidanny** [comment]
i got a problem button with body image... it wont run: 
let button = new Buttons(media,[{body:'kopi ireng'},{body:'kopi setarbak'},{body:'kapal api'}]);

but this command can send the image.
msg.reply(media);

**Comment by mamoru-69** [comment]
i try it
button show good,
but in whatsapp web,
not on whatsapp app just show blank

**Comment by sam-the-tutor** [comment]
> i got a problem button with body image... it wont run: let button = new Buttons(media,[{body:'kopi ireng'},{body:'kopi setarbak'},{body:'kapal api'}]);
> 
> but this command can send the image. msg.reply(media);

is there a solution to this issue yet, i am facing the same here. when you send a button with media, it doesn't arrive on the receiver.

**Comment by nelson8013** [comment]
Please can you show me how to send a button as a response to a message from the sender? 

I can't seem to find an example to follow.

Thank you in advance

**Pull request merged**
