### PR TITLE
fix [#2510] - Protocol error (Runtime.callFunctionOn): Promise was collected 

### PR DESCRIPTION
**Pull request by Sansekai**
# PR Details
I added ``await`` in every before sending message.

## Description
Fix for https://github.com/pedroslopez/whatsapp-web.js/issues/2510

## Related Issue
https://github.com/pedroslopez/whatsapp-web.js/issues/2510

## How Has This Been Tested
I have tried and tested it on my own Bot using the whatsapp-web.js module

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by elhumbertoz — APPROVED** [review]

**Review by jairocedenoadrian — APPROVED** [review]

**Review by elhumbertoz — APPROVED** [review]

**Review by Elyasir — APPROVED** [review]

**Review by jpdev01 — APPROVED** [review]

**Review by paulinhovba — APPROVED** [review]

**Review by videjunior — APPROVED** [review]

**Review by oswaldosierra — COMMENTED** [review]
This is the version I'm using and it works fine.

**Comment by jpdev01** [comment]
> Still happens here, altough much less frequently when applying this patch, i wonder if other functions are causing this (such as getChat and getMedia)

Here too

**Comment by DevAlexandreCR** [comment]
> > Still happens here, altough much less frequently when applying this patch, i wonder if other functions are causing this (such as getChat and getMedia)
> 
> Here too

Here too since today

**Comment by acrerega** [comment]
Here too

> > Still happens here, altough much less frequently when applying this patch, i wonder if other functions are causing this (such as getChat and getMedia)
> 
> Here too

**Review by alechkos — COMMENTED** [review]
The addition of the `await` keyword is unnecessary and incorrect in all the cases where you’ve added it

**Comment by JohnnyLove777** [comment]
> The addition of the `await` keyword is unnecessary and incorrect in all the cases where you’ve added it

So we need to figure out how to deal with this issue soon as possible, it's a critical one.
The "Protocol error (Runtime.callFunctionOn): Promise was collected]

**Comment by alechkos** [comment]
@JohnnyLove777 
> So we need to figure out how to deal with this issue soon as possible, it's a critical one.

it's easy 
you have to use Promises and asynchronous functions correctly

**Comment by JohnnyLove777** [comment]
> @JohnnyLove777
> 
> > So we need to figure out how to deal with this issue soon as possible, it's a critical one.
> 
> it's easy you have to use Promises and asynchronous functions correctly

Awesome bro! Can you provide some content or a tutorial on how to correctly use asynchronous functions or promises to avoid this kind of crashing?

**Comment by pguardiario** [comment]
this happened to me when page.evaluate returned a promise the didn't resolve. The fix was to make sure it resolves or rejects.

**Pull request closed without merging**
