### PR TITLE
Added getCommonGroups to branch main and fixed it.

### PR DESCRIPTION
**Pull request by Schwartzblat**

### CODE REVIEW

**Comment by shirser121** [comment]
What is the difference between `window.mR.findModule('findCommonGroups')[0].findCommonGroups` to `window.Store.Wap.commonGroupsFind`?

**Comment by Schwartzblat** [comment]
I will check.

**Comment by Schwartzblat** [comment]
Ok you are right. I will fix it.

**Comment by shirser121** [comment]
Perfect!
Also, maybe we should return chatGroup instead of chat id

**Comment by Schwartzblat** [comment]
> Perfect! Also, maybe we should return chatGroup instead of chat id

I don't think it's a good idea because sometimes you want to just get the number of the chats or use the ids.
What are you saying about adding options parameter so you can choose what output you want?

**Comment by shirser121** [comment]
> I don't think it's a good idea because sometimes you want to just get the number of the chats or use the ids. What are you saying about adding options parameter so you can choose what output you want?

I think it's unnecessary, because as you say, we can get the chats by the ida

**Comment by Schwartzblat** [comment]
> > I don't think it's a good idea because sometimes you want to just get the number of the chats or use the ids. What are you saying about adding options parameter so you can choose what output you want?
> 
> I think it's unnecessary, because as you say, we can get the chats by the ida

So leave it as it is?

**Comment by shirser121** [comment]
> > > I don't think it's a good idea because sometimes you want to just get the number of the chats or use the ids. What are you saying about adding options parameter so you can choose what output you want?
> > 
> > 
> > I think it's unnecessary, because as you say, we can get the chats by the ida
> 
> So leave it as it is?

Yes.
In my project i did exactly the same.
I planned to crate a PR but you did it perfectly

**Review by shirser121 — APPROVED** [review]
LGTM

**Comment by Schwartzblat** [comment]
> > > > I don't think it's a good idea because sometimes you want to just get the number of the chats or use the ids. What are you saying about adding options parameter so you can choose what output you want?
> > > 
> > > 
> > > I think it's unnecessary, because as you say, we can get the chats by the ida
> > 
> > 
> > So leave it as it is?
> 
> Yes. In my project i did exactly the same. I planned to crate a PR but you did it perfectly

Lol thanks. In my project I am using the multidevice branch so the solution that I uploaded first is compatible to both.

**Review by purpshell — APPROVED** [review]
lgtm

**Comment by Schwartzblat** [comment]
@shirser121 can you review again?

**Review by purpshell — APPROVED** [review]
Again, lgtm

**Review by shirser121 — APPROVED** [review]
Hope this will get merge

**Comment by pedroslopez** [comment]
Closing as this was included as part of the MD merge #889

**Pull request closed without merging**
