### PR TITLE
fix: linkPreview returning BUNDLE error by Wap link preview generator

### PR DESCRIPTION
**Pull request by jaovitubr**
fix: Overriding Store.Wap.queryLinkPreview function that when set linkPreview true it returns BUNDLE error

### CODE REVIEW

**Comment by tuyuribr** [comment]
Hey, thanks for contributing! So somethings about this:
If wa can't make a preview of a link we should not do anything
or
if we should do something, we should keep the new dependencies at a minimum. We can use pup to do what you are doing so maybe we should just keep using pup.

And we should default linkPreview to false

**Comment by PurpShell** [comment]
> Hey, thanks for contributing! So somethings about this: If wa can't make a preview of a link we should not do anything or if we should do something, we should keep the new dependencies at a minimum. We can use pup to do what you are doing so maybe we should just keep using pup.
> 
> And we should default linkPreview to false

THIS. WhatsApp even said in their official notes about MD that link previews may not function as normal. 

I don't think this project is made to replicate any behavior other than that

**Comment by PurpShell** [comment]
I don't even know how to review this

**Comment by PurpShell** [comment]
Oh, and the reason the link preview generation is broken is because of Wap itself, it's deprecated in MD. I am positive that there is a module for this in MD, so try to find it

**Comment by PurpShell** [comment]
reopen a new pr since changes

**Pull request closed without merging**
