### PR TITLE
fixed vote_update

### PR DESCRIPTION
**Pull request by aryeharmon**
# PR Details

fixed poll_update event to work in webpack-exodus

## Description

fixed poll_update event to work in webpack-exodus

## Related Issue
#3169 ([add vote_update to support 2.3xx. Poll events.](https://github.com/pedroslopez/whatsapp-web.js/issues/3169))

## How Has This Been Tested

example.js file added example

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tofers** [comment]
Are you getting events in these edits?  I tried transferring to a new branch. And the events just didn't happen.

I'll have to check anyway.

**Comment by leviscd** [comment]
your PR don't is work!

**Comment by BenyFilho** [comment]
I followed these steps changes and I did a change and it worked for me

CHANGES:
File index.js
+ line 22 PollVote: require('./src/structures/PollVote'),

**Comment by barjak213** [comment]
> I followed these steps changes and I did a change and it worked for me
> 
> CHANGES: File src/index.js
> 
> * line 22 PollVote: require('./src/structures/PollVote'),
> 
> Because there are two files index.js, one in folder /structures and another in the /src

Are you sure?

**Comment by BenyFilho** [comment]
> > I followed these steps changes and I did a change and it worked for me
> > CHANGES: File src/index.js
> > 
> > * line 22 PollVote: require('./src/structures/PollVote'),
> > 
> > Because there are two files index.js, one in folder /structures and another in the /src
> 
> Are you sure?

It was 6 months ago, now things have changed

**Pull request closed without merging**
