### PR TITLE
Fix: Cannot read properties of undefined (reading 'features')

### PR DESCRIPTION
**Pull request by shirser121**
Find MD backend without features

### CODE REVIEW

**Comment by shirser121** [comment]
Solve https://github.com/pedroslopez/whatsapp-web.js/issues/1406

**Review by purpshell — APPROVED** [review]
+1

**Comment by salvuccicarlos** [comment]
The changes works correctly!

**Comment by Eonus21** [comment]
You don't change this in all places of code. There are two places in Client.js and LegacySessionAuth.js
https://github.com/Eonus21/whatsapp-web.js/commit/7525268d8f264c70c1cda865ebf1c59196e2bdae

**Comment by PurpShell** [comment]
i'm going to change the head branch of this to a new branch, so people can use `npm install github:pedroslopez/whatsapp-web.js#features_fix`

**Pull request merged**
