### PR TITLE
Add contact_change_state event. 

### PR DESCRIPTION
**Pull request by soncemvo**
With this change you can recieve "typing" or "recording" events of your contacts

### CODE REVIEW

**Comment by tuyuribr** [comment]
I think that you are missing the "window.Store.Presence"

**Comment by soncemvo** [comment]
> I think that you are missing the "window.Store.Presence"

No, its available in Store

**Comment by tuyuribr** [comment]
> 
> 
> > I think that you are missing the "window.Store.Presence"
> 
> No, its available in Store

My bad, so the only thing to change is doublequotes to single quotes

**Comment by soncemvo** [comment]
> > > I think that you are missing the "window.Store.Presence"
> > 
> > 
> > No, its available in Store
> 
> My bad, so the only thing to change is doublequotes to single quotes

done

**Review by purpshell — APPROVED** [review]

**Comment by PurpShell** [comment]
@pedroslopez couldn't this be used to update the presence to be gotten by #553 ? You mentioned stuff about setTimeout, seems like storing the presence in some kind of variable and then accessing them by the function viable.

**Comment by pedroslopez** [comment]
Thanks for contributing! This is something that's definitely been asked for in the past.

My concern with this is that, from previous experience, WhatsApp Web doesn't subscribe to the Presence of everybody, so the results of the events you're getting may be unexpected. You might want to listen for state changes of a particular user, but WhatsApp Web might not be subscribed to their presence.

So, this brings up a few questions for me: Has this changed? If not, could we instead write a function to subscribe to someone's presence? How many contacts does WhatsApp Web subscribe to by default?

**Comment by fatihmesse** [comment]
I use the this function, at startup is it working but later than throw all chat status and stop working. How can ı fix it?
Ekran Resmi 2022-10-30 15 59 12

**Pull request closed without merging**
