### PR TITLE
Added option to return qrcode as a base64 image.

### PR DESCRIPTION
**Pull request by victormga**
Added a flag that can be passed in options to return the qrcode as base64 image.

### CODE REVIEW

**Comment by victormga** [comment]
anything on this?

**Comment by fadlee** [comment]
Love this changes, no need to regenerate the qr code

**Comment by parthibd** [comment]
We can easily encode the QR code data as an image for the event data in WWJs . I don't think this feature is necessary as it can be implemented easily in userland code .

**Comment by victormga** [comment]
closing as i'm making the pr's separated.

**Pull request closed without merging**
