### PR TITLE
fixed version id number

### PR DESCRIPTION
**Pull request by saifkhan7865**
# PR Details

## Description

this is the fix for [version Id not exists error](https://github.com/pedroslopez/whatsapp-web.js/issues/2067)

## How Has This Been Tested

I have tested on the browser on a real instance

image

## Types of changes

- [ ] Dependency change 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by karankarakoti — COMMENTED** [review]
Yup, its working now

**Review by beesaycheese — APPROVED** [review]

**Review by lost0star — APPROVED** [review]

**Review by anupammaurya6767 — APPROVED** [review]

**Review by wacns — APPROVED** [review]
Works for me!

**Review by sudoMoshe — APPROVED** [review]
this fixed the bug for me Error: Evaluation failed: Error: addParticipants: incoming change missing version id

**Comment by wslleal19** [comment]
@PurpShell any chance to implement this solution?

**Review by AlexSalgadoM — APPROVED** [review]
A mí me funciono esta solución para corregir el error con addParticipants y RemoveParticipants

**Review by purpshell — APPROVED** [review]
lgtm @tuyuribr

**Review by tuyuribr — APPROVED** [review]

**Comment by ChetanMotghare** [comment]
getting error   
 this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^

TypeError: data.id.id.substring is not a function

**Comment by karankarakoti** [comment]
this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
^

TypeError: data.id.id.substring is not a function
getting this error

**Pull request merged**
