### PR TITLE
Added function sendMessageToId to send message without chat before

### PR DESCRIPTION
**Pull request by SimiPrambos**
same as **sendMessage** function but if you don't have conversation before, you can use **sendMessageToId** .. check the example.js how to use this function

### CODE REVIEW

**Comment by GliderCodes** [comment]
Hey there, just wondering what the id is? is it the number or what else could it be? Also if I have a number how do I take an ID from it if it's different.

**Review by pedroslopez — CHANGES_REQUESTED** [review]
Sorry for the long wait! I finally had the chance to check this out. It works great, thanks for contributing!

A little has changed in regards to sending messages, so please rebase with the latest changes and take a look at how the new `sendMessage` function works, specifically the change from `Store.SendMessage` to `WWebJS.sendMessage` and the returning of the new message. It shouldn't be too much of a change.

Just a little comment was added as well. Thanks again for this!

**Comment by tarikhagustia** [comment]
any update on this PR? i need this function too :)

**Comment by pedroslopez** [comment]
Hi @tarikhagustia ! It seems the original PR author has gone inactive. I will clean this up and merge it later tonight.

**Comment by pedroslopez** [comment]
superseeded by #52

**Pull request closed without merging**
