### PR TITLE
Fix: INTRO_IMG_SELECTOR not working

### PR DESCRIPTION
**Pull request by pauloracunha**
# PR Details

INTRO_IMG_SELECTOR is a DOM selector to recognize that the message screen has loaded.

## Description

I added additional selectors to the intro image, as well as adding a selector to the profile logo

## How Has This Been Tested

- I scanned the qrcode
- I checked if the 'ready' event was fired

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by ibarria0 — APPROVED** [review]
This works for me.

**Comment by GathsaraH** [comment]
Also not working for me

**Comment by GathsaraH** [comment]
Changes made in this PR works for me. please merge this.

**Comment by kogeva** [comment]
This works for me.

**Comment by akr1999** [comment]
#2490 

Merge this Fix for INTRO_IMG_SELECTOR

**Review by akr1999 — CHANGES_REQUESTED** [review]
const INTRO_IMG_SELECTOR = '[data-icon="search"]'

This will work till infinity as its not possible for WhatsApp to change search icon easily.

**Review by AndyTargino — APPROVED** [review]

**Comment by iAhtasham** [comment]
I tried 
```
const INTRO_IMG_SELECTOR = '[data-icon="search"]';
```
but it didnt work for me :(, client is not getting ready.

**Comment by GathsaraH** [comment]
> I tried
> 
> ```
> const INTRO_IMG_SELECTOR = '[data-icon="search"]';
> ```
> 
> but it didnt work for me :(, client is not getting ready.

Try this
`const INTRO_IMG_SELECTOR = '[data-icon="chat"],[data-icon="intro-md-beta-logo-dark"],[data-icon="intro-md-beta-logo-light"],[aria-label="profile photo"]';`

**Comment by tuyuribr** [comment]
Dupe of #2474

**Comment by iAhtasham** [comment]
> const INTRO_IMG_SELECTOR = '[data-icon="chat"],[data-icon="intro-md-beta-logo-dark"],[data-icon="intro-md-beta-logo-light"],[aria-label="profile photo"]';

Thank you for your reply, but its still not working :(
`const qrcode = require('qrcode-terminal');
const { Client, RemoteAuth } = require('whatsapp-web.js');
const mongoose = require('mongoose');
const { MongoStore } = require('wwebjs-mongo');

async function createClient(setStatus, setQr) {
    // Connect to MongoDB
    await mongoose.connect('mongodb://127.0.0.1:27017/whatsapp', {
        useNewUrlParser: true,
        useUnifiedTopology: true
    });

    // Create a new session store
    const store = new MongoStore({ mongoose: mongoose });
    const client = new Client({
        authStrategy: new RemoteAuth({
            store: store,
            backupSyncIntervalMs: 300000 // Backup the session data every 5 minutes
        })
    });

    
    
    client.on('qr', (qr) => {
        console.log(qr)
        setStatus("auth_failed")
        setQr(qr);
        //qrcode.generate(qr, {small: true});
    });
    

    client.on('authenticated', () => {
        setStatus("authenticated")
        console.log('Client is authenticated!');
    });

    client.on('auth_failure', (msg) => {
        // Fired if session restore was unsuccessful
        console.log("auth failed")
        setStatus("auth_failed")
        console.error('Authentication failure!', msg);
    });

    client.on('disconnected', (reason) => {
        console.log("disconnected")
        setStatus("auth_failed")
        console.log('Client was logged out', reason);
    });

    await new Promise(resolve => {
        console.log("ready")
        setStatus("authenticated")
        client.on('ready', resolve);
        client.initialize();
    });

    console.log('Client is ready!');

    return client;
}

module.exports = createClient;
`
this is my code

**Pull request closed without merging**
