### PR TITLE
auto login from saved session data

### PR DESCRIPTION
**Pull request by gabriel-tandil**
save and read session data for login in a json file

### CODE REVIEW

**Comment by gabriel-tandil** [comment]
you have a beautiful project here, a very small contribution.

**Comment by pedroslopez** [comment]
Thanks for the contribution! 

Personally, I think I would prefer the library not write these things to disk and opt for whoever is using it to take care of that instead. In my eyes, there are a couple of things that may cause it to not work as intended, so I would leave it up to the user to decide what is best for what they're trying to do.

**Comment by pedroslopez** [comment]
@gabriel-tandil Looking at this again, I think we can do it. For whatever reason when I first reviewed this I assumed it was going into the library, but upon checking again I see that this is merely a contribution to the example. In this case, I think it's ok we provide something as a base for other people to build upon. Regardless, this whole example.js thing is less than ideal and I'd like to have a proper guide up at some point. 

If you want, you can reopen this and we can get it merged. My only comments would be to rename `config.json` to maybe `session.json` and try to avoid the use of `var`, instead opting for `const` whenever possible and `let` where it's not.

**Comment by iamshouvikmitra** [comment]
I want to auto generate new session if the session details found in ./session.json is old. How is that possible?

**Comment by pedroslopez** [comment]
@iamshouvikmitra An "auth_failure" event is emitted when a session restore is not possible. You can use this to detect it and delete the existing session.

**Comment by iamshouvikmitra** [comment]
Yeah, @pedroslopez  would you mind sharing a snippet of the same implementation. I am a little confused about killing the previous session. And defining a new client.


Ex - 
```
let client = new Client({session : cfg})


client.on('auth_failure', () => {
    client = new Client ()
})

doesn't seems to be an working solution.
```

**Pull request closed without merging**
