### PR TITLE
added catch in sendMessage function for handling the error

### PR DESCRIPTION
**Pull request by dan89farhan**
added 
.catch(error => { throw error }); 
at line 389

please approve it for better handling of errors

### CODE REVIEW

**Comment by pedroslopez** [comment]
Thanks for contributing. Is there a specific case where you are getting errors that I can try out?

**Comment by dan89farhan** [comment]
yes, send a message with the wrong number. for e.g: 666666666677. since it is an invalid number then it should return an error message. but now the application gets crashed please update the code with catch functionality.

**Comment by pedroslopez** [comment]
I see... but this fix doesn't seem to do anything since it's throwing the same error back. If this is something that happens in your case you should catch the error yourself when calling the sendMessage function, or check if the number is valid before by using `client.isRegisteredUser()`

**Comment by dan89farhan** [comment]
how do I suppose to catch the error when client.js in not throwing any error it just get crashed with error UnhandledPromiseRejectionWarning: Error

**Comment by Aliyss** [comment]
adding a ```try { your_code } catch (e) { console.log(e) }``` should work good enough.

**Pull request closed without merging**
