### PR TITLE
Multi-device Support [TESTERS NEEDED!]

### LINKED ISSUE #758: Regarding the Multi-device BETA. (CLICK HERE)
I opened this issue to discuss the multi-device beta that just got announced and available to everyone at the latest version of the WhatsApp and WhatsApp Business beta.

We are in the final stages of supporting this beta update, and we need your help. Visit #889 to help test. 

ps: pinned because of so many issues

### PR DESCRIPTION
**Pull request by purpshell**
**NOTICE:** Merge is waiting for multi-device's release.  

**ANOTHER NOTICE:** #889 has been opened since I changed plans (instead of having a fork, i'll have a multidevice branch and merge all the enhancements we can add later)

Suggested changes to bring multi-device beta support. 

Milestones:
- [x] Add envisioned file management system
- [ ] Test all functions using tests

Known issues - Things to fix: 
- [x] Send Messages
- [ ] Random "BUNDLE" errors when getting data is expected. We are working hard to identify the source of this issue, though I think it might have to do with serialization of data to be sent between Puppeteer and the browser environment.  
- [ ] #847 compatibility.
 
 
Known issues - not fixable: 
- Battery percentage information & events are gone
- Phone information gone too (phone, os, os version, wa version)
- Also you are now required to use "clientId" in the Client constructor's options parameter for more than one session. Look at [this](https://github.com/PurpShell/whatsapp-web.js/blob/330b33ed03722a2b674eec47756f44b7fddc72cf/src/Client.js#L32)
- Browserless / Remote Access (browserWSEndpoint) might not work as well (saving sessions) (re-writing soon to support)
- WhatsApp is now storing session data, contacts, chats, messages all in the browser, with no clear way to fetch the data, meaning we are resorting to using the fileSystem, and the files need to be updates in MS intervals if you are getting a lot of messages. Please find a way to use the filesystem. 

<a name="test">Testers</a>: 

Hey, this PR needs people to perform tests, mainly people with multidevice-enabled devices. Hopefully you can test and upload your logs, and if there is any issue hope that we can fix it and make it better. Thank you for your contributions so far. 
 - Steps: 
    - Clone this branch of repo (https://github.com/pedroslopez/whatsapp-web.js/tree/multidevice) or (`npm i github:pedroslopez/whatsapp-web.js#multidevice`)
    - Perform tests (/tests/ in the directory (please look at the readme before running anything))
    - Errors? Success? Send your results here, use a [pastebin](https://pastebin.com) to submit your logs, though.

### CODE REVIEW

**Comment by PurpShell** [comment]
Pushing code to send message

**Comment by tinyCoder32** [comment]
Wap.queryExist is always undefined on Multi-Device BETA.

**Comment by alpires** [comment]
> Wap.queryExist is always undefined on Multi-Device BETA.

Same issue here. Some idea to fix it?

**Comment by PurpShell** [comment]
A bunch of methods have gone haywire :D, there seems to be some update to the serialization that it won't work from code, but it's fine in the browser. a whole bunch of get* methods have gone error mode on my machine

**Comment by YehudaEi** [comment]
Hi, 
I have now checked the draft offered here, it should be noted that there is a problem that when you run the code again and it loads the session from json, it returns a login error.

Yehuda.

**Comment by gabrielrey37** [comment]
The session has empty credentials

**Comment by PurpShell** [comment]
> Hi,
> I have now checked the draft offered here, it should be noted that there is a problem that when you run the code again and it loads the session from json, it returns a login error.
> 
> Yehuda.

yeah exactly why I'm creating a file management system. The session format changed

**Comment by PurpShell** [comment]
Look at #758 for actual research, and for implementation look here

**Comment by ariona** [comment]
> Wap.queryExist is always undefined on Multi-Device BETA.

have you found the solution for this queryExist issue?

**Comment by tinyCoder32** [comment]
> > Wap.queryExist is always undefined on Multi-Device BETA.
> 
> have you found the solution for this queryExist issue?

Not yet. Let me know if you do please.

**Comment by makanSukros** [comment]
> Suggested changes to bring multi-device beta support.
> 
> Milestones:
> 
> * [ ]  Add envisioned file management system
> * [ ]  Test all functions using tests
> 
> Known issues - Things to fix:
> 
> * [x]  Send Messages

Im try resume session in md, not work

**Comment by PurpShell** [comment]
> > Suggested changes to bring multi-device beta support.
> > Milestones:
> > 
> > * [ ]   Add envisioned file management system
> > * [ ]   Test all functions using tests
> > 
> > Known issues - Things to fix:
> > 
> > * [x]   Send Messages
> 
> Im try resume session in md, not work

my file management system is not done, i'll push today

**Comment by makanSukros** [comment]
Ehnancement suggestion

const dirPathExist = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
        var isFirstConnection = false;
        if (!fs.existsSync(path.join(dirPathExist, 'Default'))) {
            //create head directory
            isFirstConnection = true;
            const dirPath = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
            await Util.createNestedDirectory(dirPath);
            this.options.puppeteer.userDataDir = dirPath;
        }else{
            this.options.puppeteer.userDataDir = dirPathExist;
        }

And 

then part 

if (!isFirstConnection) {

**Comment by makanSukros** [comment]
@PurpShell im test function Wap like queryexist get profile picture function is stal without any error, i think any problem with user

**Comment by PurpShell** [comment]
> Ehnancement suggestion
> 
> const dirPathExist = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
>         var isFirstConnection = false;
>         if (!fs.existsSync(path.join(dirPathExist, 'Default'))) {
>             //create head directory
>             isFirstConnection = true;
>             const dirPath = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
>             await Util.createNestedDirectory(dirPath);
>             this.options.puppeteer.userDataDir = dirPath;
>         }else{
>             this.options.puppeteer.userDataDir = dirPathExist;
>         }
> 
> And 
> 
> then part 
> 
> if (!isFirstConnection) {

Why though? I don't think we need this

**Comment by makanSukros** [comment]
> > Ehnancement suggestion
> > const dirPathExist = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
> > var isFirstConnection = false;
> > if (!fs.existsSync(path.join(dirPathExist, 'Default'))) {
> > //create head directory
> > isFirstConnection = true;
> > const dirPath = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
> > await Util.createNestedDirectory(dirPath);
> > this.options.puppeteer.userDataDir = dirPath;
> > }else{
> > this.options.puppeteer.userDataDir = dirPathExist;
> > }
> > And
> > then part
> > if (!isFirstConnection) {
> 
> Why though? I don't think we need this

for showing qrcode, before enhancement, i cannot get qr code from listener, must scan from chrome

**Comment by PurpShell** [comment]
> Ehnancement suggestion
> 
> const dirPathExist = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
> var isFirstConnection = false;
> if (!fs.existsSync(path.join(dirPathExist, 'Default'))) {
> //create head directory
> isFirstConnection = true;
> const dirPath = path.join(process.cwd(), this.options.dataPath, this.id ? 'session-' + this.id : 'session');
> await Util.createNestedDirectory(dirPath);
> this.options.puppeteer.userDataDir = dirPath;
> }else{
> this.options.puppeteer.userDataDir = dirPathExist;
> }
> 
> And
> 
> then part
> 
> if (!isFirstConnection) {

I added this (optimized), thanks for noticing

**Comment by sankalpsm** [comment]
await client.isRegisteredUser(number) is unable to check number on whatsapp or not

**Comment by PurpShell** [comment]
> await client.isRegisteredUser(number) is unable to check number on whatsapp or not

People have said that above, i will work on it after 3 days

**Comment by makanSukros** [comment]
> await client.isRegisteredUser(number) is unable to check number on whatsapp or not

I want solution for this 

// Injected.js
Im added this to injected js 

var modulesByCondition = Object.keys(window.mR.modules);
    modulesByCondition.forEach(async function(mKey) {
      mod = window.mR.modules[mKey];
      if (typeof mod !== 'undefined') {
        if(typeof mod.default != 'undefined'){
          if(mod.default.toString().includes('Should not reach queryExists MD')){
              window.Store.CheckRegisteredOnWhatsApp = mod.default;
            }
        }else{
             if(mod.markComposing && mod.markPaused && mod.markRecording){
              window.Store.ChatPresence = mod;
            }
        }
      }
    });

**Comment by makanSukros** [comment]
> CheckRegisteredOnWhatsApp

and apply this to Client.js

async isRegisteredUser(id) {
        return await this.pupPage.evaluate(async (id) => {
            // let result = await window.Store.Wap.queryExist(id);

            const contactWid = window.Store.WidFactory.createWid(id);
            let result = await window.Store.CheckRegisteredOnWhatsApp(contactWid);
            console.log('result', result);

            const wid = result?.wid?._serialized;
            return ((wid !== null) && (typeof wid !== 'undefined'));
        }, id);
    }
    
    async getProfilePicUrl(contactId) {
        return await this.pupPage.evaluate(async id => {
            var x = await window.Store.ProfilePicThumb.find(id);
            var urlPict = x?.eurl;
            return urlPict;
        }, contactId);
    }

**Comment by makanSukros** [comment]
apply on Chat.js

```
async sendStateRecording() {
        return this.client.pupPage.evaluate(async(chatId) => {
            
            const chat = window.Store.Chat.get(chatId);
            if (chat) {
                await Store.ChatPresence.markRecording(chat);
                return true;
            }else{
                return false;
            }

        }, this.id._serialized);
    }

async clearState() {
        return this.client.pupPage.evaluate(async(chatId) => {

            const chat = window.Store.Chat.get(chatId);
            if (chat) {
                await Store.ChatPresence.markPaused(chat);
                return true;
            }else{
                return false;
            }

        }, this.id._serialized);
    }

async sendStateTyping() {
        return this.client.pupPage.evaluate(async(chatId) => {

            const chat = window.Store.Chat.get(chatId);
            if (chat) {
                await Store.ChatPresence.markComposing(chat);
                return true;
            }else{
                return false;
            }
            
        }, this.id._serialized);
    }
```

**Comment by makanSukros** [comment]
For phone information i think md doesn't care about the device used, because it doesn't need to retrieve the low battery and no internet connection information

**Comment by sidikhanrei** [comment]
Send message error when trying using link in message body

`
Error: Evaluation failed: Error: Unexpected null or undefined: BUNDLE
    at t.default (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:56:308391)
    at Object.t.get (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:56:335880)
    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:5:6790)
    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:2:105235)
    at t.default.write (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:2:378144)
    at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:2:90554)
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35021)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35232)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35291
    at ExecutionContext._evaluateInternal (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.sendMessage (\src\Client.js:649:32)
`

**Comment by ariona** [comment]
> > await client.isRegisteredUser(number) is unable to check number on whatsapp or not
> 
> I want solution for this
> 
> // Injected.js
> Im added this to injected js
> 
> ```
> var modulesByCondition = Object.keys(window.mR.modules);
>     modulesByCondition.forEach(async function(mKey) {
>       mod = window.mR.modules[mKey];
>       if (typeof mod !== 'undefined') {
>         if(typeof mod.default != 'undefined'){
>           if(mod.default.toString().includes('Should not reach queryExists MD')){
>               window.Store.CheckRegisteredOnWhatsApp = mod.default;
>             }
>         }else{
>              if(mod.markComposing && mod.markPaused && mod.markRecording){
>               window.Store.ChatPresence = mod;
>             }
>         }
>       }
>     });
> ```

Running this, resulting error below:
```
Uncaught (in promise) TypeError: mod.default.toString is not a function
```

**Comment by ariona** [comment]
> > > await client.isRegisteredUser(number) is unable to check number on whatsapp or not
> > 
> > 
> > I want solution for this
> > // Injected.js
> > Im added this to injected js
> > ```
> > var modulesByCondition = Object.keys(window.mR.modules);
> >     modulesByCondition.forEach(async function(mKey) {
> >       mod = window.mR.modules[mKey];
> >       if (typeof mod !== 'undefined') {
> >         if(typeof mod.default != 'undefined'){
> >           if(mod.default.toString().includes('Should not reach queryExists MD')){
> >               window.Store.CheckRegisteredOnWhatsApp = mod.default;
> >             }
> >         }else{
> >              if(mod.markComposing && mod.markPaused && mod.markRecording){
> >               window.Store.ChatPresence = mod;
> >             }
> >         }
> >       }
> >     });
> > ```
> 
> Running this, resulting error below:
> 
> ```
> Uncaught (in promise) TypeError: mod.default.toString is not a function
> ```

solved by adding extra condition:
```js
if( mod.default.toString && mod.default.toString().includes('Should not reach queryExists MD')) { }
```

**Comment by sankalpsm** [comment]
@PurpShell & @makanSukros  Thanks



client.on('qr', (qr) => {
    // NOTE: This event will not be fired if a session is specified.
    console.log('QR RECEIVED', qr);
});

is not getting fired

**Comment by PurpShell** [comment]
> @PurpShell & @makanSukros Thanks
> 
> client.on('qr', (qr) => {
> // NOTE: This event will not be fired if a session is specified.
> console.log('QR RECEIVED', qr);
> });
> 
> is not getting fired

it should be though


as for the bundle errors you guys are getting, this is what I've been concerned with since I started work on this PR, still can't get to the main source of the issue... These bundle errors are popping up on chats, contacts, incoming messages etc..

Seems like a serialization issue, since executing the same code returns a perfect result.

**Comment by makanSukros** [comment]
> Send message error when trying using link in message body
> 
> `Error: Evaluation failed: Error: Unexpected null or undefined: BUNDLE at t.default (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:56:308391) at Object.t.get (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:56:335880) at Function.encrypt (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:5:6790) at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:2:105235) at t.default.write (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:2:378144) at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.e39859bf8358eb1e7271.js:2:90554) at Generator.next (<anonymous>) at t (https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35021) at s (https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35232) at https://web.whatsapp.com/vendor1~bootstrap_qr.8d5b7620b726968ba154.js:2:35291 at ExecutionContext._evaluateInternal (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async ExecutionContext.evaluate (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16) at async Client.sendMessage (\src\Client.js:649:32)`

Its not good solution, for temporary solution set linkPreview to false 
Ref: https://docs.wwebjs.dev/global.html#MessageSendOptions

**Comment by aryarasen** [comment]
> > @PurpShell & @makanSukros Thanks
> > client.on('qr', (qr) => {
> > // NOTE: This event will not be fired if a session is specified.
> > console.log('QR RECEIVED', qr);
> > });
> > is not getting fired
> 
> it should be though
> 
> as for the bundle errors you guys are getting, this is what I've been concerned with since I started work on this PR, still can't get to the main source of the issue... These bundle errors are popping up on chats, contacts, incoming messages etc..
> 
> Seems like a serialization issue, since executing the same code in the browser console returns a perfect result.

Hi, has this issue been solved?

**Comment by PurpShell** [comment]
> > > @PurpShell & @makanSukros Thanks
> > > client.on('qr', (qr) => {
> > > // NOTE: This event will not be fired if a session is specified.
> > > console.log('QR RECEIVED', qr);
> > > });
> > > is not getting fired
> > 
> > it should be though
> > 
> > as for the bundle errors you guys are getting, this is what I've been concerned with since I started work on this PR, still can't get to the main source of the issue... These bundle errors are popping up on chats, contacts, incoming messages etc..
> > 
> > Seems like a serialization issue, since executing the same code in the browser console returns a perfect result.
> 
> Hi, has this issue been solved?

Look in the 1st comment ( i will always update it to cross out bugs etc

**Review by androettop — APPROVED** [review]

**Comment by Eonus21** [comment]
Why file system was used here for session storing? Is is possible to make it as earlier - session object in authenditication event?

**Comment by makanSukros** [comment]
> Why file system was used here for session storing? Is is possible to make it as earlier - session object in authenditication event?

Yes, because multi devices using  indexed db to save chats, contacts, etc

**Comment by krasymyr** [comment]
thanks for the hard work. 
will there be a way to serialize the session data like before, to export/re-use the it ?

**Comment by PurpShell** [comment]
> Why file system was used here for session storing? Is is possible to make it as earlier - session object in authenditication event?

I think I said in my main comment that it will soon be re-written. Though using JSON/Objects is not feasible anymore since there is now some LARGE data stored, no way to fetch from WA, and it's needed or consider the client useless. 

I will export each DB as an object of it's own, and the data needs to be updated every second or so, so no not able.

**Comment by PurpShell** [comment]
> thanks for the hard work.
> will there be a way to serialize the session data like before, to export/re-use the it ?

answered above.

**Comment by PurpShell** [comment]
NOTICE: #889 has been opened, just to fix some branch issues.

**Comment by javargasm** [comment]
messages sent to groups are never read, even though members have already viewed them.

**Comment by dreanmer** [comment]
It's working pretty stable in my environment with chrome headless, the only issue I've faced was with profile picture when receiving an message:
```
await contact.getProfilePicUrl();
```

its exploding (even with browser opened):
```
/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: h
    at ExecutionContext._evaluateInternal (/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getProfilePicUrl (/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/node_modules/whatsapp-web.js/src/Client.js:764:28)
    at async PrivateContact.getProfilePicUrl (/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/node_modules/whatsapp-web.js/src/structures/Contact.js:120:16)
    at async Client.<anonymous> (/home/alexandre/Projects/ovoxx/ovoxx-atendimento/docker/whatsapp-web/server.multidevice.js:71:25)

```

**Comment by PurpShell** [comment]
Please talk in the newer PR. Thanks.

**Pull request closed without merging**
