### PR TITLE
fix: Fix client-side message rendering issue when sending attachements through the library

### LINKED ISSUE #778: Message sent from me (bot) ends up formatted incorrectly.
### Bug description
When sending some types of media (**edited images**, either cropped or painted, **video** or **gifs**) result in the Message received by the client having improper formatting.

For example: When sending an edited image the "message.type" appears as "image" but "message.hasMedia" as **false** and "body" turns into a lower quality base64 string of the image data.
message.downloadMedia() returns undefined

### Reproduction steps
1. Start client
2. Send edited image, video or gif to anyone (including oneself)

### Expected behavior 
Message received should be formatted properly with media downloadable and body the same as sent.

### Relevant code
`client.on("message_create", async  (message) => {
    console.log(message);
}
`

### Environment (please complete the following information):
**WhatsApp**
 - Account type [Standard / Business]: Standard 
 - Device OS [iOS / Android]: Android
 - WhatsApp Web version [run `await client.getWWebVersion()`]: 2.2126.11

**Library**
 - Browser [Chrome / Chromium]: Chromium
 - NodeJS version (`node -v`): v14.17.3
 - npm or yarn version (`npm -v`): 6.14.13
 - whatsapp-web.js version: 1.13.2

**Other**
 - Operating system (the one running node) [Linux / MacOS / Windows]: Windows 10 Pro
 - Operating system version (ex. Windows 10):  Windows 10 Pro

### Additional context
Message with error:
image

Message without error:
image

### LINKED ISSUE #960: Sending bas64 Media Converts to String on web refresh
### Bug description
I'm sending QR Code generated with
```const QRCode = require("easyqrcodejs-nodejs");```

It sends an image but after refresh or app restart the image on web converts to a long string

image

### Reproduction steps

image
image
Send Image
Reload

### Expected behavior 
Send a qr code image and when reload remain QR Code

WhatsApp

Account type [Standard / Business]: Standard
Device OS [iOS / Android]: Android
WhatsApp Web version [run await client.getWWebVersion()]: 2.2142.12
Library

Browser [Chrome / Chromium]: Chrome
NodeJS version (node -v): v14.18.0
npm or yarn version (npm -v): yarn 1.22.15
whatsapp-web.js version: "whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#multidevice"
Other

Operating system (the one running node) [Linux / MacOS / Windows]: Linux
Operating system version (ex. Windows 10): Ubuntu 21

### LINKED ISSUE #1807: Send image get blur and random code after reload web whatsapp
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

send media with image get blur
and become random code after reload web wa
image

### Expected behavior

3 days ago it is normal, and i found it blur since yesterday

### Steps to Reproduce the Bug or Issue

i have search issues and nothing except 2020 issue

### Relevant Code

async function sendmedia(id, text, mime, base64, filename) {
  const chatWid = window.Store.WidFactory.createWid(id + "@c.us");
  const result = await window.Store.QueryExist(chatWid);
  if (!result || result.wid === undefined) {
    return false;
  } else {
    const chat = await window.Store.Chat.find(chatWid);
    // let intoption = {
    //   attachment: new MessageMedia(mime, base64, filename),
    //   caption: text,
    // };
    window.WWebJS.sendMessage(chat, "", {
      attachment: new MessageMedia(mime, base64, filename),
      caption: text
    });
    return true;
  }
}

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

windows
newest wawebjs

### Additional context

_No response_

### LINKED ISSUE #1874: Message media sent blurry images
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I use this code to send a image, 
```
app.post("/whatsapp/", async (req, res) => {
   
  const {number, message, media} = req.body;
  console.log(req.body.number)
  
  console.log(String(number), message, media);
  if (botActivo) {
    await client.sendMessage(`${number}@c.us`, String(message).replace(/--/g, "\n"));
    if (media){
      const mediaToSend = MessageMedia.fromFilePath(media);
      await client.sendMessage(`${number}@c.us`, mediaToSend);
    }
    return res.send({message: "succ"});
  } else {
    return res.status(500).send({message: "error"});
  }
});
```
Got the result,  a blurry image in the whatsapp window like this.
image

### Expected behavior

like this:
image

### Steps to Reproduce the Bug or Issue

see code.

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

OS: win 10
PhoneOS :  --
whatsapp-web.js 1.18.4
whatsapp web : 2.2247.5
node.js : v18.12.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by purpshell**
# PR Details

This PR aims to fix the issues with rendering an attachement sent through WWebJS in the GUI after the reload/restart of the client.

image

## Description

It seems the issue was that the mediaData prop was not getting properly serialized and added to the message object, which has been reflected & changed in MD. Now in MD, (in the code) the prop is also serialized and appended to the msg object in WhatsApp Web code. I have tested all types of attachments and this seems to work properly

## Motivation and Context

This fix will make the UI more enjoyable and appropriate. The issue was in how the message type `"chat"` was not affected after the concatenation of the attachment options, and so on reload the body (the thumbnail) was eventually just rendered as text rather than an image. This change was needed to make the library a better experience overall to people who use the GUI in co-ordinance with the library. This also fixes other issues like the instability of message type after sending a message with attachments.

## How Has This Been Tested

Fully tested on a session with normal WhatsApp on Android. Please try this pull request and help us assure it is fully functioning, it should be though as it now mimics 1:1 how it is sent in WA.

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by tuyuribr — APPROVED** [review]

**Comment by zahmadz** [comment]
it's work 

image

**Comment by bhavya32** [comment]
Works for me :)

**Comment by pedroslopez** [comment]
@PurpShell FYI: I had to revert this in https://github.com/pedroslopez/whatsapp-web.js/pull/1932 because it broke sending stickers.

**Comment by liranrevivo** [comment]
@pedroslopez can you please investigate for a way to re-add this without making breaking changes?
This fix was very critical for me..

**Comment by folk-connect** [comment]
@PurpShell Can you fix it without breaking stickers and create a new PR. This is an important fix for me

**Comment by PurpShell** [comment]
.

**Pull request merged**
