### PR TITLE
Fix message.delete

### LINKED ISSUE #2104: delete message bug
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

c:\Users\AbcdefG\Documents\js\mk1\wnbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'promises')
    at t.sendRevokeMsgs (https://web.whatsapp.com/main.5040d1c4cee6edb1de7c.js:6:945694)
    at Object.current (https://web.whatsapp.com/main.5040d1c4cee6edb1de7c.js:5:813909)
    at https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:336611
    at f.<anonymous> (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:332782)
    at f._triggerEvents (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:50:441809)
    at f.trigger (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:50:440381)
    at f.sendRevokeMsgs (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:786753)
    at __puppeteer_evaluation_script__:6:41
    at ExecutionContext._evaluateInternal (c:\Users\AbcdefG\Documents\js\mk1\wnbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (c:\Users\AbcdefG\Documents\js\mk1\wnbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Message.delete (c:\Users\AbcdefG\Documents\js\mk1\wnbot\node_modules\whatsapp-web.js\src\structures\Message.js:439:9)
    at async Client.<anonymous> (c:\Users\AbcdefG\Documents\js\mk1\wnbot\wire.js:233:17)

Node.js v19.8.1

### Expected behavior

ddelete message

### Steps to Reproduce the Bug or Issue

!delete with mension

### Relevant Code

        if (msg.body.startsWith('!delete')){
            if(msg.hasQuotedMsg){
                await msg.getQuotedMessage().then(data => data.delete(true))
                }
                
                //await oldmsg.delete(true)
            }

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

windows 11

### Additional context

i using chrome canary

### LINKED ISSUE #2120: I'm getting an error when deleting a message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
let m = new Message(client, {
        id: {
            _serialized: serialized,
            id: msgid
        },
    });
    m.delete(true);
```

This is the error I get;
```
   throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'promises')
```

### Expected behavior

getting error

### Steps to Reproduce the Bug or Issue

error

### Relevant Code

let m = new Message(client, {
        id: {
            _serialized: serialized,
            id: msgid
        },
    });
    m.delete(true);

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

nodejs 18
whatsappwebjs realase
chrome
windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wictornogueira**
# PR Details

This pr tries to fix message.delete 🤷🏻 

## Related Issue

fixes #2120
fixes #2104

## Motivation and Context

Yes

## How Has This Been Tested

<s>It hasn't</s>

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by RC047** [comment]
> # PR Details
> This pr tries to fix message.delete 🤷🏻
> 
> ## Description
> ## Related Issue
> #2115 #2104
> 
> ## Motivation and Context
> Yes
> 
> ## How Has This Been Tested
> It hasn't
> 
> ## Types of changes
> * [ ]  Dependency change
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Checklist
> * [x]  My code follows the code style of this project.
> * [x]  I have updated the documentation accordingly (index.d.ts).

Its work! thanks

**Review by diegofemello — COMMENTED** [review]
Worked to me, thanks

**Comment by gkp1** [comment]
Worked, thanks

**Comment by z2ro** [comment]
It's working! Thank you!

**Comment by pirranet** [comment]
Funcionando...

**Comment by FilipeCamillo** [comment]
Funcionando...

**Comment by CJRMedeiros123** [comment]
Working here!!

**Comment by amiruldev20** [comment]
no work in private chat

**Review by purpshell — APPROVED** [review]

**Comment by Santosl2** [comment]
Doesn't work for me..

My issue: #2131

**Comment by diegofemello** [comment]
> Doesn't work for me..
> 
> My issue: #2131

Not merged yet, change branch to test if it worked

**Comment by Santosl2** [comment]
> > Doesn't work for me..
> > My issue: #2131
> 
> Not merged yet, change branch to test if it worked
> 
> Package.json "whatsapp-web.js": "github:wictornogueira/whatsapp-web.js#fix_message_delete"

Yes man, i did it

**Comment by Horgun** [comment]
Funcionou aqui tb

**Pull request closed without merging**
