### PR TITLE
Feat: Add chat_removed and chat_archived events

### PR DESCRIPTION
**Pull request by wictornogueira**
## Description

Adds two new events:
- **chat_removed**: triggered when a chat gets deleted
- **chat_archived**: triggered when a chat is archived or unarchived

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by PurpShell** [comment]
@tuyuribr @aliyss @pedroslopez

**Review by purpshell — APPROVED** [review]

**Comment by Aliyss** [comment]
I remember implementing this a long time ago with chat pins and so on... Did it get lost in the mean time?

**Comment by wictornogueira** [comment]
> I remember implementing this a long time ago with chat pins and so on... Did it get lost in the mean time?
> 
> @PurpShell

I've just now checked your prs and doesn't seem like it... I could easily be blind though 🤔

**Review by aliyss — APPROVED** [review]
lgtm

**Comment by Aliyss** [comment]
> > I remember implementing this a long time ago with chat pins and so on... Did it get lost in the mean time?
> > 
> > @PurpShell
> 
> I've just now checked your prs and doesn't seem like it... I could easily be blind though 🤔
> 

My bad. Sorry. @wictornogueira 

The events were missing.

**Pull request merged**
