### PR TITLE
Api whatshap

### PR DESCRIPTION
**Pull request by Nopalmangkok**
const { Client } = require('whatsapp-web.js');

const client = new Client();

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    if (msg.body == '!saya mau order) {
        msg.reply('Halo kak, selamat datang! 
Ini dengan siapa dan posisi dimana ada yang bisa kami bantu?
Mau pesan untuk usia kandungan berapa bulan? ');
    }
});

### CODE REVIEW

**Comment by Nopalmangkok** [comment]
const { Client } = require('whatsapp-web.js');

const client = new Client();

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    if (msg.body == '!saya mau order) {
        msg.reply('Halo kak, selamat datang! 
Ini dengan siapa dan posisi dimana ada yang bisa kami bantu?
Mau pesan untuk usia kandungan berapa bulan? ');
    }
});

**Comment by Nopalmangkok** [comment]
const { Client } = require('whatsapp-web.js');

const client = new Client();

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    if (msg.body == '!saya mau order) {
        msg.reply('Halo kak, selamat datang! 
Ini dengan siapa dan posisi dimana ada yang bisa kami bantu?
Mau pesan untuk usia kandungan berapa bulan? ');
    }
});

**Comment by xdarkki** [comment]
?

**Comment by hamza-masoud** [comment]
have you any problem with name name of the file (example.js)
I think this the perfect name for description the content of the file

**Comment by hamza-masoud** [comment]
@pedroslopez please close the pull request
I don't need to see crazy things here in this repo, it should be more professional

**Comment by d0v3riz** [comment]
Kalo gak paham github jangan pull2 gajelas dong kak

**Comment by d0v3riz** [comment]
> @pedroslopez please close the pull request I don't need to see crazy things here in this repo, it should be more professional

He's from my country, I can't understand why he could do that. Maybe just for fun. The best way is to close this pull.

**Comment by pedroslopez** [comment]
Closed as spam

**Pull request closed without merging**
