### PR TITLE
Hotfix: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')

### PR DESCRIPTION
**Pull request by wictornogueira**
# PR Details

## Description

Nothing special

## Related Issue

- #1913

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by qaisarirfan — APPROVED** [review]

**Review by vladkucherov — APPROVED** [review]

**Review by Eonus — APPROVED** [review]

**Comment by matricce** [comment]
1. Optional chaining can't be used, It's not compatible with node v12
2. This is a workaround, not a fix

**Comment by wictornogueira** [comment]
> 1. Optional chaining can't be used, It's not compatible with node v12
> 2. This is a workaround, not a fix

**Comment by heloisarsantos** [comment]
Didn't work for me

**Comment by Helvio88** [comment]
This prevents pptr from starting up, I think it needs to be addressed soon, even if as a workaround.

**Review by Helvio88 — APPROVED** [review]
It works on my case.

**Review by guilhermesperb — APPROVED** [review]

**Review by santiramirezc — APPROVED** [review]

**Review by GonzagaGustavo — APPROVED** [review]
Solved my problem

**Review by egondadalt — APPROVED** [review]
it's working

**Review by bmultisofts — APPROVED** [review]
It is just a hotfix. needs to check if this is recommended and doesn't break other things

**Review by bmultisofts — APPROVED** [review]
Hotfix working. Seems like it didn't break any other features for me

**Comment by zerodark17** [comment]
d
gives that error when using removeParticipants

**Review by sleepinggautama — APPROVED** [review]
Works for me, and does not break anything.

Edit:
I also re-released this fix on npm for anyone who want a quick substitute until the main fix is released.
https://www.npmjs.com/package/@sleepinggautama/whatsapp-web.js

**Review by edywdono — COMMENTED** [review]
its work!!

**Review by oguzhan51511 — APPROVED** [review]

**Comment by CJRMedeiros123** [comment]
Work from me!

**Comment by zerodark17** [comment]
this fix breaks the library and breaks methods like sendRemoveParticipants
image

**Comment by diegoquirozramirez** [comment]
This is the solution
image

**Review by MazanLabeeb — COMMENTED** [review]
worked for me

**Review by sachhu — APPROVED** [review]
Working for me

**Review by saintlypioneer — APPROVED** [review]
This change solved the issue mentioned

**Review by brenogalinari — APPROVED** [review]

**Comment by gamersindo1223** [comment]
Didn't solve the issues,
almost all group feature like removeparticipants is broken

**Review by Rakambda — APPROVED** [review]

**Comment by AlbertoJCS** [comment]
where can i locate this file that shows in the image

**Comment by slottler** [comment]
Thanks for the hotfix!!!  I've read all the comments.  But I'm using npm and still having the problem.  Could somebody maybe write a Simple explanation of what we need to do to get the hotfix working?  Apologies for my ignorance!

**Review by msolis6686 — APPROVED** [review]
Me funcionó perfectamente. Gracias!

**Comment by anthonywebster** [comment]
same problem

**Review by C0rellana — APPROVED** [review]
Works for me!

**Review by anthonywebster — APPROVED** [review]
Work for me!!!

**Comment by pedroslopez** [comment]
Thanks @wictornogueira !

This fix wasn't compatible with older versions of nodejs due to the use of the `?` operator. I pushed #1930 to address this.

Please update to v1.19.1 to fix the issue.

**Comment by wictornogueira** [comment]
> Thanks @wictornogueira !
> 
> This fix wasn't compatible with older versions of nodejs due to the use of the `?` operator. I pushed #1930 to address this.
> 
> Please update to v1.19.1 to fix the issue.

Np
It was never meant to be a proper fix, more like a hack to help ease the transition 😅

2.2301 seems to be finished rolling out, btw (in latam, at least)

**Pull request closed without merging**
