### PR TITLE
Include payment info [Review needed]

### PR DESCRIPTION
**Pull request by tuyuribr**
Include new facebook pay data ( maybe we should put the "Payment Status too"

### CODE REVIEW

**Comment by tuyuribr** [comment]
paymentStatus possible codes :
0:UNKNOWN_STATUS
1:PROCESSING
2:SENT
3:NEED_TO_ACCEPT
4:COMPLETE
5:COULD_NOT_COMPLETE
6:REFUNDED
7:EXPIRED
8:REJECTED
9:CANCELLED
10:WAITING_FOR_PAYER
11:WAITING

**Comment by tuyuribr** [comment]
Usage :
```
client.on('message', async msg=> {
     if (msg.type === 'payment') {
                let payment = await msg.getPayment();
     }
});
```

**Review by purpshell — APPROVED** [review]
nice

Best regards, 

[PurpShell](https://github.com/PurpShell)

**Comment by tuyuribr** [comment]
This is working like a charm in 2.2126.11

**Review by purpshell — APPROVED** [review]
lgtm

**Comment by tuyuribr** [comment]
@pedroslopez

**Review by aliyss — APPROVED** [review]
approved -> code looks good

**Pull request merged**
