### PR TITLE
Fix types of Buttons class

### PR DESCRIPTION
**Pull request by noamzaks**

### CODE REVIEW

**Review by purpshell — APPROVED** [review]
LGTM++!

**Comment by tuyuribr** [comment]
LGTM

**Comment by user3470** [comment]
Could this be Why MD buttons are not working?

**Comment by pedroslopez** [comment]
@user3470 no, this is just for documentation and typescript usage

**Review by pedroslopez — APPROVED** [review]
Thanks for this! I fixed up some of the jsdoc types since they were invalid

**Pull request merged**
