### PR TITLE
Update User agent

### PR DESCRIPTION
**Pull request by YehudaEi**
I encountered errors because of this (it says that the chrome version needs to be updated)

### CODE REVIEW

**Review by hamza-masoud — APPROVED** [review]

**Review by YehudaEi — COMMENTED** [review]
.

**Comment by YehudaEi** [comment]
@tuyuribr For me it solved the problem...

**Review by marianeitor — APPROVED** [review]
User agent is set to a newer one and It make sense because It was getting old. Need to be updated every couple of months

**Review by shirser121 — APPROVED** [review]
LGTM

**Review by TemaSM — APPROVED** [review]

**Review by purpshell — APPROVED** [review]
i guess this needs to be addressed quick, @pedroslopez

**Review by tuyuribr — APPROVED** [review]
We need to make a bot to update this each month

**Pull request merged**
