### PR TITLE
fix compatibility issues with WhatsApp Web 2.2208.7

### LINKED ISSUE #1310: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'randomId')
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'randomId')
    at __puppeteer_evaluation_script__:12:61
    at ExecutionContext._evaluateInternal (myproject/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (myproject/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (myproject/node_modules/whatsapp-web.js/src/Client.js:192:9)
```

### Expected behavior

no crash

### Steps to Reproduce the Bug or Issue

Use whatsapp-web.js v1.15.8

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

OS: Ubuntu 20.04.3 Linux on Raspberry Pi
Phone OS: Android
whatsapp-web.js version 1.15.8
Node.js version v16.14.0

WhatsApp Web version [run await client.getWWebVersion()]:
um... crash during `client.initialize()` .. how to run this?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pedroslopez**
close #1310 #1305

### CODE REVIEW

**Review by maltarget — APPROVED** [review]

**Comment by tuyuribr** [comment]
Tested, it is working !

Environment

OS:  Windows 10 with Ryzen
Phone: Android running non biz, non md
whatsapp-web.js version github:pedroslopez/whatsapp-web.js#fix-2.2208.7
Node.js version v14.15.0.
WaWeb version: 2.2208.7

**Comment by pedroslopez** [comment]
Unsure on the release for this yet since we're kind of in a weird spot where the old version (2.2206.9) is still being delivered by default, though the serviceworker is updating to 2.2208.7 for subsequent runs, which is why clearing the cache/deleting userDataDir works.

I'm looking into intercepting the initial request so that we can make whatsapp-web.js "stick" to a specific version until the library gets an update so this is less of an issue later down.

**Comment by pedroslopez** [comment]
Released [1.16.4-alpha.0](https://www.npmjs.com/package/whatsapp-web.js/v/1.16.4-alpha.0) - will do a mainline release when whatsapp web fully updates

**Comment by 0xT-001** [comment]
I use the isRegisteredUser interface to check the phonenumber which has been registered in whatsapp, it returns false

**Comment by iriobf** [comment]
> I use the isRegisteredUser interface to check the phonenumber which has been registered in whatsapp, it returns false

Same problem here

**Review by Misbb — APPROVED** [review]

**Pull request merged**
