### PR TITLE
fix: Cannot read properties of undefined (reading 'Socket') #1235

### LINKED ISSUE #1235: Error on create store object - Uncaught TypeError: Cannot read properties of undefined (reading 'Socket')
window.Store.AppState = window.mR.findModule('STREAM')[0].Socket;

Uncaught TypeError: Cannot read properties of undefined (reading 'Socket')

### PR DESCRIPTION
**Pull request by KeruMx**
fix #1235 
thanks to @[janke184](https://github.com/janke184) for find the module
i tested and work fine this module

### CODE REVIEW

**Review by NowDev — APPROVED** [review]
It fixed the problem for me, thanks.

**Review by maikelohcfg — APPROVED** [review]
Tested and it works properly on MD. Thanks

**Comment by jtourisNS** [comment]
Worked perfectly fine for me on main branch too. 

As this is for MultiDevice, I created a new PR but for main branch with this same fix

https://github.com/pedroslopez/whatsapp-web.js/pull/1249

**Review by pedroslopez — APPROVED** [review]
Thanks!

**Pull request merged**
