### PR TITLE
Update Client.js

### PR DESCRIPTION
**Pull request by brunox64**
fix detection of WhatsApp load event

# PR Details

During initialization of whatsapp-web.js it didn't emiting READY event, with my analysis i had detected an issue with css selector used for load event, i fixed it and test then the event now is emitted, the error is because the selector of homescreen image of WhatsApp change depending of what is the version of WhatsApp is used for

## Description

I changed 
from: const INTRO_IMG_SELECTOR = '[data-icon=\'chat\']';
to: const INTRO_IMG_SELECTOR = '[data-icon="chat"],[data-icon="intro-md-beta-logo-dark"],[data-icon="intro-md-beta-logo-light"]';

## Related Issue
During initialization of whatsapp-web.js it didn't emiting READY event

## Motivation and Context
During initialization of whatsapp-web.js it didn't emiting READY event, with my analysis i had detected an issue with css selector used for load event, i fixed it and test then the event now is emitted, the error is because the selector of homescreen image of WhatsApp change depending of what is the version of WhatsApp is used for

## How Has This Been Tested
I was used the fixed version of whatsapp-web.js in production and works fine for distinct versions of WhatsApp

## Types of changes
I changed 
from: const INTRO_IMG_SELECTOR = '[data-icon=\'chat\']';
to: const INTRO_IMG_SELECTOR = '[data-icon="chat"],[data-icon="intro-md-beta-logo-dark"],[data-icon="intro-md-beta-logo-light"]';

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by leodutra** [comment]
I've just tested this, and it fixed the post-auth silence. Thanks @brunox64.

**Review by GT-Eric — APPROVED** [review]

**Comment by GT-Eric** [comment]
LGTM

**Review by oriyadid — APPROVED** [review]
LGTM, Fixed said issue on my instance.

**Comment by webidol** [comment]
Hi @brunox64 
I just tested this, and it resolved the post-auth silence issue. However, the 'getProfilePicUrl' method of the 'contact' object is not functioning.

**Review by eduanmoldeep — APPROVED** [review]
LGTM

**Comment by eduanmoldeep** [comment]
@pedroslopez please review and merge soon, there are multiple fixes on hold, and every new bot needs these custom configs to be done separately since not merged.

Requesting your kind attention <3

**Review by r4faelaugusto — APPROVED** [review]

**Review by radianx — APPROVED** [review]

**Review by yusufneeson — APPROVED** [review]

**Comment by Flag-King** [comment]
It's worked for me too! Thanks!
Also, 'logicaly', I need to re-build and restart backend service. : )

**Pull request closed without merging**
