### PR TITLE
fix(typings): getChats, getChat, List Section, Row and Buttons Media

### PR DESCRIPTION
**Pull request by viniciusgdr**
I noticed that the Chat typings were wrong in my tests. Upon checking, I found that it returned either GroupChat or PrivateChat.
To differentiate the two, a boolean isGroup was made on each. Being able to differentiate only with a true and false.

About the lists:
The lists contained any in their definition, making it impossible for the user to know what would be sent.

The buttons:
Without MessageMedia typing, the user would not know that he could send images and videos on it.

### CODE REVIEW

**Comment by viniciusgdr** [comment]
unstale

**Comment by viniciusgdr** [comment]
unstale

**Review by ToledoSDL — APPROVED** [review]

**Comment by viniciusgdr** [comment]
unstale

**Comment by viniciusgdr** [comment]
unstale

**Comment by viniciusgdr** [comment]
unstlae

**Comment by viniciusgdr** [comment]
unstale

**Comment by viniciusgdr** [comment]
unstale

**Review by purpshell — APPROVED** [review]
Weird methodology but looks good

**Pull request closed without merging**
