### PR TITLE
feat: send audio with waveform

### LINKED ISSUE #2270: Voice information issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is what I sent, there are no water ripples：
image

This is sent using WhatsApp with water ripples：

image

### Expected behavior

can see water ripples

### Steps to Reproduce the Bug or Issue

1. send a   xxx.ogg  .

2.   sendAudioAsVoice: true

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

whatsapp-web.js: Latest version
node: 16.15.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

### - [How Has the PR Been Tested](#tests)
- [**The environment the PR was tested on**](#env)
- [**I want to test this PR**](#pr-testing)
- [**I have an issue while testing this PR**](#pr-testing-issue)

### - [Types of Changes](#types-of-changes)

---

## Description <a href="#description" id="description"/>
PR adds the functionality to include a generated waveform for audio messages sent as voice.
Additionally, when voice messages are resent, they will now include the waveform of their original message.

## Special Thanks
- @edgardmessias for the implementation that is referenced from his [commit](https://github.com/wppconnect-team/wa-js/commit/290ebfefe6021b3d17f7fdfdda5545bb0473b26f)

## Related Issue <a href="#related-issues" id="related-issues"/>
PR fixes #2270 

## Usage Example (also added to [example.js](https://github.com/alechkos/whatsapp-web.js/blob/89d98bb01afaa6d651b89f67459a9a4852be067b/example.js#L143)) <a href="#usage-example" id="usage-example"/>

```js
client.on('message', async (msg) => {
    if (msg.body === '!sendaudioasvoice' && msg.hasQuotedMsg) {
        const quotedMsg = await msg.getQuotedMessage();
        if (quotedMsg.hasMedia && quotedMsg.type === 'audio') {
            const audio = await quotedMsg.downloadMedia();
            await client.sendMessage(msg.from, audio, { sendAudioAsVoice: true });
        }
    }
});
```

## How Has This Been Tested <a href="#tests" id="tests"/>
It has been tested by sending audio files from a specified path and resending voice messages.

<details><summary>

### Tested On <a href="#env" id="env"/>
</summary>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS v1.21.0
    - WWeb v2.2322.15
    - Node v16.17.1
    - Chrome 114.0.5735.199
</details>

### To test this PR by yourself you can run one of the following commands: <a href="#pr-testing" id="pr-testing"/>
```powershell
# NPM
npm install github:alechkos/whatsapp-web.js#waveform
# YARN
yarn add github:alechkos/whatsapp-web.js#waveform
```

### If you encounter any issues while testing this PR, please provide in a comment: <a href="#pr-testing-issue" id="pr-testing-issue"/>
1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWwebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got

## Types of Changes <a href="#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tofers** [comment]
It looks good. I'll check it out.

```
throw new Error('Failed to generate waveform', e);
```

This throw will not allow you to send a message.  If the waves aren't loaded, you won't be able to send a voice message.  And if they are not loaded, you need to send a voice message without waves.

Ideally, you should make loading waves optional.

**Comment by alechkos** [comment]
@tofers I think the waveform generation by default it's a good idea as it is the default wweb behavior also, but in order to ensure the voice message is sent ill make changes to send a voice message without a waveform in the case of waveform generation failure.
What do yoiu think?

**Comment by tofers** [comment]
> What do you think?

Now it's good.  I'll write back after I've tested it on different files

**Review by tuyuribr — APPROVED** [review]

**Review by aliyss — APPROVED** [review]

**Review by Jcvp1 — COMMENTED** [review]
Muito bom

**Pull request merged**
