### PR TITLE
send message without chat before

### PR DESCRIPTION
**Pull request by sahalMoidu**
Implemented changes mentioned in SimiPrambos PR #28
To reflect new code structure
https://github.com/pedroslopez/whatsapp-web.js/pull/28

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by fernandolcardoso** [comment]
Is this the final version? I downloaded the master version with the changes applied and I am experiencing problems when forwarding messages to people who are not on my list.

```
(node:6864) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'id' of undefined
    at __puppeteer_evaluation_script__:11:50
    at ExecutionContext._evaluateInternal (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\Page.js:860:43)
    at Page.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:112:23)
    at Client.sendMessage (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\src\Client.js:275:47)
    at Client.client.on (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\sessions.js:78:10)
    at Client.emit (events.js:198:13)
    at Client.initialize (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\src\Client.js:240:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by sahalMoidu** [comment]
There was another pull request that was committed moments earlier. Could you please download the latest code and check.

Please let me know your results

**Comment by sahalMoidu** [comment]
@fernandolcardoso  could you please verify if your chat list isn't empty. ie you need to have at least one chat message in the chat list

**Comment by fernandolcardoso** [comment]
Hello @sahalMoidu, the idea of ​​this topic is that we can forward it to people who are not on our list.

Anyway, I will download it again and run new tests.

**Comment by fernandolcardoso** [comment]
Hello @, I believe it is the same problem.

```
(node:3624) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'id' of undefined
    at __puppeteer_evaluation_script__:11:50
    at ExecutionContext._evaluateInternal (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\Page.js:860:43)
    at Page.<anonymous> (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\node_modules\puppeteer\lib\helper.js:112:23)
    at Client.sendMessage (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\src\Client.js:275:47)
    at Client.client.on (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\sessions.js:78:10)
    at Client.emit (events.js:198:13)
    at Client.initialize (C:\Users\Fernando\Documents\Node\whatsapp\whatsapp\1.0.2-master\src\Client.js:240:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
```

**Comment by pedroslopez** [comment]
> Hello @sahalMoidu, the idea of ​​this topic is that we can forward it to people who are not on our list.
> 
> Anyway, I will download it again and run new tests.

His question was not whether there was an chat open for the number, but if you have any chats open with anyone else. The current solution requires at least one pre existing chat (with any user) to work

**Comment by fernandolcardoso** [comment]
Hello @pedroslopez, thanks for your return.

I did not imagine that it was necessary to have at least one contact to start new conversations.

Now everything is settled.

**Comment by Aliyss** [comment]
I will try using the addContact method I found somewhere to see if that actually allows me to circumvent the restriction

**Comment by iamshouvikmitra** [comment]
To make things clear. With this PR, one can send a message to any number having a Whatsapp account? And it doesn't require that number  to appear in our chat list (i.e, not have any previous conversation) nor have that number in our contact!

Is that correct?

**Comment by sahalMoidu** [comment]
@iamshouvikmitra that is correct. Only thing to note is that your chat list shouldn't be empty. It should contain at least one chat to any other person.

**Comment by pedroslopez** [comment]
> @iamshouvikmitra that is correct. Only thing to note is that your chat list shouldn't be empty. It should contain at least one chat to any other person.

@sahalMoidu Maybe an empty chat list should throw a more descriptive error in this case?

**Comment by sahalMoidu** [comment]
@pedroslopez  Yeah sure. Maybe in the next commit

**Pull request merged**
