### PR TITLE
feat: add or remove labels

### PR DESCRIPTION
**Pull request by tofers**
# PR Details

Update labels for chats

## Description

Removing, adding and updating a label for a chat/chats

## Related Issue

https://github.com/pedroslopez/whatsapp-web.js/issues/1910
https://github.com/pedroslopez/whatsapp-web.js/issues/1209

## Motivation and Context

My clients ask for a way to mark the chats. And for the web version, deletion of labels is available, why not

## How Has This Been Tested

I tested my business account, I also added an example. Tested on Linux

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Comment by tuyuribr** [comment]
Sounds good, we need testers for this.

**Comment by tofers** [comment]
Corrected the conflict

**Comment by liranrevivo** [comment]
Can you please merge this?
@tofers @PurpShell @pedroslopez

**Comment by usystemsoftwares** [comment]
Hello!!! Will this be merged soon? I want to build a project and this feature would be ideal

**Comment by SceLPI** [comment]
Tested and would be a great addition, Thanks

**Review by usystemsoftwares — APPROVED** [review]

**Review by itshedimisawi — APPROVED** [review]
Just tested it, works perfectly

**Review by lucasduarte0 — APPROVED** [review]
Working perfectly until moment

**Review by codebossdev — APPROVED** [review]

**Review by aliyss — APPROVED** [review]
lgtm

**Comment by iloukou** [comment]
how to use

**Pull request merged**
